services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: bcs_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bcs_dump.sql:/docker-entrypoint-initdb.d/bcs_dump.sql

  web:
    build: .
    container_name: bcs_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db

volumes:
  db_data:
  static_volume:
  media_volume:
