# Generated by Django 5.2.1 on 2025-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("osoby", "0027_alter_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.CreateModel(
            name="KategoriaPiosenki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
            ],
            options={
                "verbose_name": "Kategoria piosenki",
                "verbose_name_plural": "Kategorie piosenek",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Piosenka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=255, verbose_name="Tytuł")),
                ("autor", models.CharField(max_length=255, verbose_name="Autor")),
                (
                    "tekst",
                    models.FileField(
                        blank=True,
                        help_text='Dodaj tekst w formacie .json, przykład: [{"chords": ["G", "C"], "line": "Tekst wiersza"}, {"chords": ["G", "D"], "line": "Tekst wiersza"}]',
                        upload_to="piosenki/",
                        verbose_name="Tekst w formacie .json",
                    ),
                ),
                (
                    "kategorie",
                    models.ManyToManyField(
                        blank=True,
                        to="spiewnik.kategoriapiosenki",
                        verbose_name="Kategoria piosenki",
                    ),
                ),
                (
                    "znani_czapce_autorzy",
                    models.ManyToManyField(
                        blank=True, to="osoby.osoba", verbose_name="Znani BCS autorzy"
                    ),
                ),
            ],
            options={
                "verbose_name": "Piosenka",
                "verbose_name_plural": "Piosenki",
                "ordering": ["tytul"],
            },
        ),
    ]
