# Generated by Django 5.2.1 on 2025-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spiewnik", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piosenka",
            name="tekst_alternatywny",
            field=models.FileField(
                blank=True,
                help_text='Dodaj tekst w formacie .json, przykład: [{"chords": ["G", "C"], "line": "Tekst wiersza"}, {"chords": ["G", "D"], "line": "Tekst wiersza"}]',
                upload_to="piosenki/",
                verbose_name="Tekst alternatywny (np. tłumaczenie) w formacie .json",
            ),
        ),
    ]
