# Generated by Django 5.2.1 on 2025-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spiewnik", "0002_piosenka_tekst_alternatywny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piosenka",
            name="autor",
            field=models.CharField(blank=True, max_length=255, verbose_name="Autor"),
        ),
        migrations.AlterField(
            model_name="piosenka",
            name="tekst",
            field=models.FileField(
                blank=True,
                help_text='\n        Dodaj tekst w formacie .json, przykład:\n        [\n          {"tekst": "Tekst wiersza", "chwyty": ["C", "D"]}, \n          {"tekst": "Tekst wiersza", "chwyty": ["G", "D"]},\n          {"tekst": "", "chwyty": []},\n          {"tekst": "Po ostatniej linii nie dajemy przecinka", "chwyty": ["Am"]}\n        ]\n        ',
                upload_to="piosenki/",
                verbose_name="Tekst w formacie .json",
            ),
        ),
        migrations.AlterField(
            model_name="piosenka",
            name="tekst_alternatywny",
            field=models.FileField(
                blank=True,
                help_text='\n        Dodaj tekst w formacie .json, przykład:\n        [\n          {"tekst": "Tekst wiersza", \n           "chwyty": ["C", "D"]}, \n          {"tekst": "Tekst wiersza", \n           "chwyty": ["G", "D"]},\n          {"tekst": "", \n           "chwyty": []},\n          {"tekst": "Po ostatniej linii nie dajemy przecinka", \n           "chwyty": ["Am"]}\n        ]\n        ',
                upload_to="piosenki/",
                verbose_name="Tekst alternatywny (np. tłumaczenie) w formacie .json",
            ),
        ),
    ]
