# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spiewnik", "0003_alter_piosenka_autor_alter_piosenka_tekst_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriapiosenki",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="piosenka",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
