# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spiewnik",
            "0004_kategoriapiosenki_search_text_piosenka_search_text",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriapiosenki",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="piosenka",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
