# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "spiewnik",
            "0009_kategoriapiosenki_search_dict_piosenka_search_dict",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kategoriapiosenki",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="piosenka",
            name="search_text",
        ),
    ]
