# Generated by Django 5.2.1 on 2025-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spiewnik", "0011_kategoriapiosenki_simple_tsv_piosenka_simple_tsv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriapiosenki",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="piosenka",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
