# Generated by Django 5.2 on 2025-05-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kronika', '0012_alter_miejsce_typ_remove_proces_zdarzenia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradycja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('okolicznosci_powstania', models.CharField(choices=[('Wyd', 'Wydarzenie'), ('Wyj', 'Wydarzenie'), ('I', 'Inne')], max_length=3, verbose_name='Okoliczności powstania')),
                ('inne', models.CharField(max_length=255, verbose_name='Inna okoliczność (wpisz)')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('wydarzenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wydarzenie', verbose_name='Wydarzenie')),
                ('wyjazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wyjazd', verbose_name='Wyjazd')),
            ],
            options={
                'verbose_name': 'Tradycja',
                'verbose_name_plural': 'Tradycje',
                'ordering': ('nazwa',),
            },
        ),
    ]
