# Generated by Django 5.2.1 on 2025-05-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0001_initial'),
        ('kronika', '0002_alter_obrazwydarzenie_options_wyjazd'),
    ]

    operations = [
    ]
