# Generated by Django 5.2 on 2025-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradycja',
            name='inne',
            field=models.CharField(blank=True, max_length=255, verbose_name='Inna okoliczność (wpisz)'),
        ),
        migrations.AlterField(
            model_name='tradycja',
            name='okolicznosci_powstania',
            field=models.CharField(choices=[('Wyd', 'Wydarzenie'), ('Wyj', 'Wyjazd'), ('I', 'Inne')], max_length=3, verbose_name='Okoliczności powstania'),
        ),
    ]
