# Generated by Django 5.2.1 on 2025-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojecie',
            options={'ordering': ('nazwa',), 'verbose_name': 'Pojęcie', 'verbose_name_plural': 'Pojęcia'},
        ),
        migrations.AlterModelOptions(
            name='zrodlo',
            options={'ordering': ('nazwa',), 'verbose_name': 'Źródło', 'verbose_name_plural': 'Źródła'},
        ),
        migrations.RemoveField(
            model_name='zrodlo',
            name='opis',
        ),
        migrations.AddField(
            model_name='zrodlo',
            name='zawartosc',
            field=models.TextField(blank=True, verbose_name='Zawartość'),
        ),
        migrations.AlterField(
            model_name='pojecie',
            name='origins',
            field=models.CharField(blank=True, choices=[('Wydarzenie', 'Na wydarzeniu czapkowym'), ('Inne', 'Inna okoliczność')], verbose_name='Pierwszy raz pojawiło się:'),
        ),
        migrations.AlterField(
            model_name='tradycjabcs',
            name='inne',
            field=models.CharField(blank=True, max_length=255, verbose_name='Inna okoliczność (wpisz):'),
        ),
        migrations.AlterField(
            model_name='zrodlo',
            name='gdzie_znalezc',
            field=models.TextField(blank=True, verbose_name='Gdzie znaleźć'),
        ),
        migrations.AlterField(
            model_name='zrodlo',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='zrodlo',
            name='nazwa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa'),
        ),
    ]
