# Generated by Django 5.2 on 2025-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0002_alter_tradycja_inne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradycja',
            name='autor_rodzaj',
            field=models.CharField(choices=[('Belg', 'Belgijska'), ('BCS', 'BCSu'), ('Faluch', 'Faluszardzka'), ('Goliard', 'Goliardzka'), ('Inne', 'Inna'), ('Korpo', 'Korporacyjna')], default='BCS', max_length=10, verbose_name='Tradycja'),
        ),
        migrations.AlterField(
            model_name='tradycja',
            name='okolicznosci_powstania',
            field=models.CharField(choices=[('I', 'Inne'), ('Wyd', 'Wydarzenie'), ('Wyj', 'Wyjazd')], max_length=3, verbose_name='Okoliczności powstania'),
        ),
    ]
