# Generated by Django 5.2.1 on 2025-07-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0003_zwyczaj_powiedzenie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="powiedzenie",
            name="autor",
        ),
    ]
