# Generated by Django 5.2 on 2025-05-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0016_przezwisko'),
        ('encyklopedia', '0003_tradycja_autor_rodzaj_and_more'),
        ('kronika', '0013_alter_miejsce_typ_alter_wydarzenie_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradycjaInnegoBractwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('autor_rodzaj', models.CharField(choices=[('Animus', 'Animus'), ('Belg', 'Belgijska'), ('Faluch', 'Faluszardzka'), ('Goliard', 'Goliardzka'), ('Inne', 'Inna'), ('Korpo', 'Korporacyjna')], max_length=10, verbose_name='Tradycja')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Tradycja innego bractwa',
                'verbose_name_plural': 'Tradycje innych bractw',
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='TradycjaBCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('autor_rodzaj', models.CharField(choices=[('Belg', 'Belgijska'), ('BCS', 'BCSu'), ('Faluch', 'Faluszardzka'), ('Goliard', 'Goliardzka'), ('Inne', 'Inna'), ('Korpo', 'Korporacyjna')], default='BCS', max_length=10, verbose_name='Tradycja')),
                ('okolicznosci_powstania', models.CharField(choices=[('I', 'Inne'), ('Wyd', 'Wydarzenie'), ('Wyj', 'Wyjazd')], max_length=3, verbose_name='Okoliczności powstania')),
                ('inne', models.CharField(blank=True, max_length=255, verbose_name='Inna okoliczność (wpisz)')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('autor_czlonek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Autor')),
                ('wydarzenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wydarzenie', verbose_name='Wydarzenie')),
                ('wyjazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wyjazd', verbose_name='Wyjazd')),
            ],
            options={
                'verbose_name': 'Tradycja',
                'verbose_name_plural': 'Tradycje',
                'ordering': ('nazwa',),
            },
        ),
        migrations.DeleteModel(
            name='Tradycja',
        ),
    ]
