# Generated by Django 5.2 on 2025-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0004_tradycjainnegobractwa_tradycjabcs_delete_tradycja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradycjainnegobractwa',
            name='autor_rodzaj',
            field=models.CharField(choices=[('Animus', 'BCS Animus'), ('Belg', 'Belgijska'), ('Faluch', 'Faluszardzka'), ('Goliard', 'Goliardzka'), ('Inne', 'Inna'), ('Korpo', 'Korporacyjna')], max_length=10, verbose_name='Tradycja'),
        ),
    ]
