# Generated by Django 5.2 on 2025-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0005_alter_tradycjainnegobractwa_autor_rodzaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bractwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('panstwo', models.CharField(choices=[('BEL', 'Belgia'), ('DNK', 'Dania'), ('FIN', 'Finlandia'), ('FRA', 'Francja'), ('DEU', 'Niemcy'), ('NOR', 'Norwegia'), ('POL', 'Polska'), ('SWE', 'Szwecja'), ('ITA', 'Włochy')], max_length=3, verbose_name='Kraj pochodzenia')),
                ('czapka', models.CharField(choices=[('CAL', 'Calotte'), ('CZA', 'Czapka'), ('FAL', 'Faluch'), ('FEL', 'Feluca'), ('I', 'Inna')], max_length=3, verbose_name='Czapka')),
                ('rok_zalozenia', models.IntegerField(default=(1111111111, 'Nie wiem'), verbose_name='Rok założenia')),
                ('wiek_tradycje', models.IntegerField(choices=[(11, 'XI'), (12, 'XII'), (13, 'XIII'), (14, 'XIV'), (15, 'XV'), (16, 'XVI'), (17, 'XVII'), (18, 'XVIII'), (19, 'XIX'), (20, 'XX'), (1111111111, 'Nie wiem')], default=(1111111111, 'Nie wiem'), verbose_name='Tradycje sięgają którego wieku')),
            ],
        ),
        migrations.CreateModel(
            name='Lengths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
