# Generated by Django 5.2 on 2025-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0006_bractwo_lengths'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lengths',
        ),
        migrations.AlterModelOptions(
            name='bractwo',
            options={'ordering': ['panstwo', 'nazwa'], 'verbose_name': 'Bractwo', 'verbose_name_plural': 'Bractwa'},
        ),
        migrations.AlterField(
            model_name='bractwo',
            name='rok_zalozenia',
            field=models.IntegerField(blank=True, verbose_name='Rok założenia'),
        ),
    ]
