# Generated by Django 5.2.1 on 2025-07-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0007_alter_bractwo_czapka"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradycjainnegobractwa",
            name="bractwo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="encyklopedia.bractwo",
                verbose_name="Bractwo",
            ),
        ),
        migrations.CreateModel(
            name="GrupaBractw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=40, verbose_name="Nazwa"),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "kraje",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="miejsca.kraj",
                        verbose_name="Kraje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupa bractw",
                "verbose_name_plural": "Grupy bractw",
                "ordering": ["nazwa"],
            },
        ),
    ]
