# Generated by Django 5.2 on 2025-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0007_delete_lengths_alter_bractwo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bractwo',
            name='rok_zalozenia',
            field=models.IntegerField(blank=True, default=(1111111111, 'Nie wiem'), verbose_name='Rok założenia'),
        ),
    ]
