# Generated by Django 5.2.1 on 2025-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0002_tradycjabcs_wydarzenie'),
        ('encyklopedia', '0009_alter_bractwo_rok_zalozenia'),
    ]

    operations = [
    ]
