# Generated by Django 5.2.1 on 2025-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0010_merge_20250514_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradycjabcs',
            name='autor_czlonek',
        ),
        migrations.RemoveField(
            model_name='tradycjabcs',
            name='wyjazd',
        ),
        migrations.AlterField(
            model_name='tradycjabcs',
            name='okolicznosci_powstania',
            field=models.CharField(choices=[('I', 'Inne'), ('Wyd', 'Wydarzenie')], max_length=3, verbose_name='Okoliczności powstania'),
        ),
    ]
