# Generated by Django 5.2.1 on 2025-07-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0010_grupabractw_rodzaj_czapki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bractwo',
            name='czapka',
        ),
        migrations.AddField(
            model_name='bractwo',
            name='grupa_bractw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyklopedia.grupabractw', verbose_name='Grupa bractw'),
        ),
    ]
