# Generated by Django 5.2.1 on 2025-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0011_remove_tradycjabcs_autor_czlonek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradycjainnegobractwa',
            name='autor_rodzaj',
            field=models.CharField(choices=[('Animus', 'BCS Animus'), ('Belg', 'Belgijska'), ('Faluch', 'Faluszardzka'), ('Goliard', 'Goliardzka'), ('Inne', 'Inna'), ('Korpo', 'Korporacyjna')], max_length=10, verbose_name='Pochodzenie tradycji'),
        ),
    ]
