# Generated by Django 5.2.1 on 2025-05-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyklopedia', '0012_alter_tradycjainnegobractwa_autor_rodzaj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradycjabcs',
            options={'ordering': ('nazwa',), 'verbose_name': 'Tradycja BCS', 'verbose_name_plural': 'Tradycje BCS'},
        ),
    ]
