# Generated by Django 5.2.1 on 2025-07-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0010_rename_bractwo_innaosoba_bractwo_do_ktorego_nalezy'),
        ('encyklopedia', '0013_alter_pojecie_origins_alter_tradycjabcs_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bractwo',
            name='zalozyciele',
            field=models.ManyToManyField(blank=True, to='czlonkowie.osoba', verbose_name='Założyciele'),
        ),
    ]
