# Generated by Django 5.2.1 on 2025-07-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0010_rename_bractwo_innaosoba_bractwo_do_ktorego_nalezy'),
        ('encyklopedia', '0016_pojecie_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiedzenie',
            name='adresaci',
            field=models.ManyToManyField(blank=True, related_name='zwiazane_zen_powiedzenia', to='czlonkowie.osoba', verbose_name='Adresat/adresaci powiedzenia'),
        ),
        migrations.AddField(
            model_name='powiedzenie',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.osoba', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='zrodlo',
            name='autorzy',
            field=models.ManyToManyField(blank=True, to='czlonkowie.osoba', verbose_name='Autorzy'),
        ),
        migrations.AddField(
            model_name='zwyczaj',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.osoba', verbose_name='Osoba, która zapoczątkowała zwyczaj'),
        ),
    ]
