# Generated by Django 5.2.1 on 2025-07-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "encyklopedia",
            "0017_powiedzenie_adresaci_powiedzenie_autor_and_more",
        ),
        ("kalendarz", "0002_alter_obrazwydarzenie_widoczne_osoby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pojecie",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendarz.wydarzenie",
                verbose_name="Wydarzenie",
            ),
        ),
        migrations.AlterField(
            model_name="tradycjabcs",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tradycje_zapoczatkowane_wydarzeniem",
                to="kalendarz.wydarzenie",
                verbose_name="Wydarzenie",
            ),
        ),
    ]
