# Generated by Django 5.2.1 on 2025-07-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0018_alter_pojecie_wydarzenie_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Zrodlo",
        ),
    ]
