# Generated by Django 5.2.1 on 2025-07-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0019_delete_zrodlo"),
        ("zrodla", "0008_alter_zrodlo_plik"),
    ]

    operations = [
        migrations.AddField(
            model_name="powiedzenie",
            name="zrodlo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.zrodlo",
                verbose_name="Źródło",
            ),
        ),
    ]
