# Generated by Django 5.2.1 on 2025-07-26 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0021_alter_powiedzenie_autor"),
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powiedzenie",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="osoby.osoba",
                verbose_name="Autor",
            ),
        ),
    ]
