# Generated by Django 5.2.1 on 2025-07-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0022_alter_powiedzenie_autor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Powiedzenie",
        ),
    ]
