# Generated by Django 5.2.1 on 2025-07-26 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("encyklopedia", "0023_delete_powiedzenie"),
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
        ("zrodla", "0008_alter_zrodlo_plik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cytat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tekst", models.TextField(verbose_name="Tekst")),
                ("kontekst", models.TextField(blank=True, verbose_name="Kontekst")),
                (
                    "adresaci",
                    models.ManyToManyField(
                        blank=True,
                        related_name="zwiazane_zen_powiedzenia",
                        to="osoby.osoba",
                        verbose_name="Adresat/adresaci powiedzenia",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.osoba",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zrodla.zrodlo",
                        verbose_name="Źródło",
                    ),
                ),
            ],
            options={
                "verbose_name": "Powiedzenie",
                "verbose_name_plural": "Powiedzenia",
                "ordering": ("tekst",),
            },
        ),
        migrations.CreateModel(
            name="Aforyzm",
            fields=[
                (
                    "cytat_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="encyklopedia.cytat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aforyzm",
                "verbose_name_plural": "Aforyzmy",
                "ordering": ["tekst"],
            },
            bases=("encyklopedia.cytat",),
        ),
    ]
