# Generated by Django 5.2.1 on 2025-07-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0024_cytat_aforyzm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cytat",
            options={
                "ordering": ("tekst",),
                "verbose_name": "Cytat",
                "verbose_name_plural": "Cytaty",
            },
        ),
    ]
