# Generated by Django 5.2.1 on 2025-07-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0025_alter_cytat_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Powiedzenie",
            fields=[
                (
                    "cytat_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="encyklopedia.cytat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Powiedzenie",
                "verbose_name_plural": "Powiedzenia",
                "ordering": ["tekst"],
            },
            bases=("encyklopedia.cytat",),
        ),
    ]
