# Generated by Django 5.2.1 on 2025-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0026_powiedzenie"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradycjabcs",
            name="pewnosc_stazu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("T", "Na pewno wcześniej się nie pojawiała"),
                    ("N", "Ale mogła pojawić się wcześniej"),
                ],
                max_length=1,
                null=True,
                verbose_name="Pewność czasu pojawienia się",
            ),
        ),
    ]
