# Generated by Django 5.2.1 on 2025-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0027_tradycjabcs_pewnosc_stazu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradycjabcs",
            name="okolicznosci_powstania",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Inne okoliczności"),
                    ("Wyd", "Na wydarzeniu czapkowym"),
                ],
                max_length=3,
                null=True,
                verbose_name="Okoliczności powstania",
            ),
        ),
        migrations.AlterField(
            model_name="tradycjabcs",
            name="pewnosc_stazu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("T", "Na pewno wcześniej się nie pojawiała"),
                    ("N", "Ale mogła pojawić się wcześniej"),
                ],
                null=True,
                verbose_name="Pewność czasu pojawienia się",
            ),
        ),
        migrations.AlterField(
            model_name="tradycjabcs",
            name="zapozyczona_czy_autorska",
            field=models.CharField(
                blank=True,
                choices=[("Z", "Zapożyczona"), ("A", "Autorka")],
                null=True,
                verbose_name="Zapożyczona czy autorska",
            ),
        ),
    ]
