# Generated by Django 5.2.1 on 2025-07-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "encyklopedia",
            "0028_alter_tradycjabcs_okolicznosci_powstania_and_more",
        ),
        ("zrodla", "0011_alter_edykt_numer_alter_ukaz_numer"),
    ]

    operations = [
        migrations.AddField(
            model_name="pojecie",
            name="zrodlo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.zrodlo",
                verbose_name="Źródło",
            ),
        ),
    ]
