# Generated by Django 5.2.1 on 2025-07-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0029_pojecie_zrodlo"),
        ("osoby", "0024_set_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cytat",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="osoby.byt",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="pojecie",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="osoby.byt",
                verbose_name="Autor pojęcia",
            ),
        ),
    ]
