# Generated by Django 5.2.1 on 2025-07-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0030_alter_cytat_autor_alter_pojecie_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="pojecie",
            name="complete",
            field=models.BooleanField(default=False, verbose_name="Notatka kompletna"),
        ),
        migrations.AlterField(
            model_name="pojecie",
            name="origins",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dok", "W dokumencie"),
                    ("I", "Inne okoliczności"),
                    ("Wyd", "Na wydarzeniu czapkowym"),
                ],
                verbose_name="Pierwszy raz pojawiło się:",
            ),
        ),
        migrations.AlterField(
            model_name="tradycjabcs",
            name="okolicznosci_powstania",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dok", "W dokumencie"),
                    ("I", "Inne okoliczności"),
                    ("Wyd", "Na wydarzeniu czapkowym"),
                ],
                max_length=3,
                null=True,
                verbose_name="Okoliczności powstania",
            ),
        ),
    ]
