# Generated by Django 5.2.1 on 2025-08-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "encyklopedia",
            "0031_pojecie_complete_alter_pojecie_origins_and_more",
        ),
        (
            "kalendarz",
            "0005_alter_wydarzeniekalendarzowe_data_rozpoczecia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pojecie",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Wydarzenie",
            ),
        ),
        migrations.AlterField(
            model_name="tradycjabcs",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tradycje_zapoczatkowane_wydarzeniem",
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Wydarzenie",
            ),
        ),
    ]
