# Generated by Django 5.2.1 on 2025-08-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0032_alter_pojecie_wydarzenie_and_more"),
        ("osoby", "0031_alter_byt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradycjabcs",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="osoby.byt",
                verbose_name="Autor tradycji",
            ),
        ),
    ]
