# Generated by Django 5.2.1 on 2025-08-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0033_alter_tradycjabcs_autor"),
        ("kalendarz", "0019_rename_depositiobeanorum_chrzest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bractwo",
            name="wydarzenia",
            field=models.ManyToManyField(
                blank=True,
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Udział w wydarzeniach",
            ),
        ),
    ]
