# Generated by Django 5.2.1 on 2025-08-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0034_bractwo_wydarzenia"),
        ("miejsca", "0005_alter_miejsce_adres"),
    ]

    operations = [
        migrations.AddField(
            model_name="bractwo",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="miejsca.uczelnia",
                verbose_name="Uczelnia",
            ),
        ),
    ]
