# Generated by Django 5.2.1 on 2025-08-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0035_bractwo_uczelnia"),
        ("kalendarz", "0019_rename_depositiobeanorum_chrzest_and_more"),
        ("miejsca", "0005_alter_miejsce_adres"),
        ("osoby", "0035_organizacja_organizacjastudencka_bractwo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bractwo",
            new_name="Bractwo1",
        ),
    ]
