# Generated by Django 5.2.1 on 2025-08-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0036_rename_bractwo_bractwo1"),
        ("osoby", "0036_alter_organizacjastudencka_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradycjainnegobractwa",
            name="bractwo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="osoby.bractwo",
                verbose_name="Bractwo",
            ),
        ),
    ]
