# Generated by Django 5.2.1 on 2025-08-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0037_alter_tradycjainnegobractwa_bractwo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bractwo1",
        ),
    ]
