# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0042_aforyzm_search_dict_grupabractw_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aforyzm",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="aforyzm",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="grupabractw",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="grupabractw",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="pojecie",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="pojecie",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="powiedzenie",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="powiedzenie",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="tradycjabcs",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="tradycjabcs",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="tradycjainnegobractwa",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="tradycjainnegobractwa",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="zwyczaj",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="zwyczaj",
            name="search_dict",
        ),
    ]
