# Generated by Django 5.2.1 on 2025-09-11 10:43

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0045_remove_aforyzm_search_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aforyzm",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="aforyzm",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="powiedzenie",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="powiedzenie",
            name="tsv",
        ),
        migrations.AddField(
            model_name="cytat",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="cytat",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
