# Generated by Django 5.2.1 on 2025-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0047_cytat_simple_tsv_grupabractw_simple_tsv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cytat",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="grupabractw",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="pojecie",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="tradycjabcs",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="tradycjainnegobractwa",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="zwyczaj",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
