# Generated by Django 5.2.1 on 2025-07-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Kadencja",
        ),
    ]
