# Generated by Django 5.2 on 2025-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadencja',
            name='zakonczenie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zakonczenie'),
        ),
    ]
