# Generated by Django 5.2 on 2025-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kadencja_zakonczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadencja',
            name='zakonczenie',
            field=models.IntegerField(blank=True, default=2010, verbose_name='Zakonczenie'),
            preserve_default=False,
        ),
    ]
