# Generated by Django 5.2.1 on 2025-07-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("zrodla", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podmiot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=40, verbose_name="Nazwa")),
                (
                    "aktualne",
                    models.BooleanField(default=True, verbose_name="Aktualne"),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podmiot",
                "verbose_name_plural": "Podmioty",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Rola",
            fields=[
                (
                    "podmiot_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="prawo.podmiot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rola jednostki w Bractwie",
                "verbose_name_plural": "Role jednostki w Bractwie",
                "ordering": ["nazwa"],
            },
            bases=("prawo.podmiot",),
        ),
        migrations.CreateModel(
            name="Struktura",
            fields=[
                (
                    "podmiot_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="prawo.podmiot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Struktura w Bractwie",
                "verbose_name_plural": "Struktury w Bractwie",
                "ordering": ["nazwa"],
            },
            bases=("prawo.podmiot",),
        ),
        migrations.CreateModel(
            name="RelacjaPrawna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tresc", models.TextField(max_length=255, verbose_name="Treść")),
                (
                    "prawo_czy_obowiazek",
                    models.CharField(
                        choices=[("P", "Prawo"), ("O", "Obowiązek")],
                        max_length=1,
                        verbose_name="Rodzaj relacji",
                    ),
                ),
                (
                    "przedawnione",
                    models.BooleanField(default=False, verbose_name="Przedawnione"),
                ),
                (
                    "dokument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zrodla.dokument",
                        verbose_name="Dokument",
                    ),
                ),
                (
                    "podmiot",
                    models.ManyToManyField(
                        blank=True, to="prawo.podmiot", verbose_name="Podmiot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Relacja prawna",
                "verbose_name_plural": "Prawa i obowiązki",
                "ordering": ["tresc"],
            },
        ),
    ]
