# Generated by Django 5.2.1 on 2025-07-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="autorzy",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="ukaz",
            name="dokument_ptr",
        ),
        migrations.DeleteModel(
            name="Edykt",
        ),
        migrations.DeleteModel(
            name="Dokument",
        ),
        migrations.DeleteModel(
            name="Ukaz",
        ),
    ]
