# Generated by Django 5.2.1 on 2025-07-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relacjaprawna",
            options={
                "verbose_name": "Relacja prawna",
                "verbose_name_plural": "Prawa i obowiązki",
            },
        ),
    ]
