# Generated by Django 5.2.1 on 2025-07-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokumenty", "0004_alter_dokument_data"),
        ("prawo", "0002_remove_dokument_autorzy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relacjaprawna",
            name="dokument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dokumenty.dokument",
                verbose_name="Dokument",
            ),
        ),
    ]
