# Generated by Django 5.2.1 on 2025-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0002_alter_relacjaprawna_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="przedawnione",
        ),
        migrations.AddField(
            model_name="relacjaprawna",
            name="aktualne",
            field=models.BooleanField(default=True, verbose_name="Aktualne"),
        ),
    ]
