# Generated by Django 5.2.1 on 2025-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0003_relacjaprawna_dokument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relacjaprawna",
            options={
                "ordering": ["tresc"],
                "verbose_name": "Relacja prawna",
                "verbose_name_plural": "Prawa i obowiązki",
            },
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="tytul",
        ),
        migrations.AddField(
            model_name="relacjaprawna",
            name="tresc",
            field=models.TextField(default="", max_length=255, verbose_name="Treść"),
            preserve_default=False,
        ),
    ]
