# Generated by Django 5.2.1 on 2025-08-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0003_remove_relacjaprawna_przedawnione_and_more"),
        ("zrodla", "0019_uchwala_walne"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relacjaprawna",
            name="dokument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.dokument",
                verbose_name="Dokument",
            ),
        ),
        migrations.CreateModel(
            name="PrawoObowiazek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktualne",
                    models.BooleanField(default=True, verbose_name="Aktualne"),
                ),
                (
                    "dokument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zrodla.dokument",
                        verbose_name="Dokument",
                    ),
                ),
                (
                    "podmiot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prawo.podmiot",
                        verbose_name="Podmiot",
                    ),
                ),
                (
                    "relacja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prawo.relacjaprawna",
                        verbose_name="Prawo/Obowiązek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prawo/Obowiązek",
                "verbose_name_plural": "Prawa i obowiązki",
                "ordering": ["podmiot", "relacja"],
            },
        ),
    ]
