# Generated by Django 5.2.1 on 2025-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0004_alter_relacjaprawna_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relacjaprawna",
            name="przedawnione",
            field=models.BooleanField(default=False, verbose_name="Przedawnione"),
        ),
    ]
