# Generated by Django 5.2.1 on 2025-08-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0004_alter_relacjaprawna_dokument_prawoobowiazek"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relacjaprawna",
            options={
                "ordering": ["tresc"],
                "verbose_name": "Relacja prawna",
                "verbose_name_plural": "Prawa i obowiązki",
            },
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="aktualne",
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="dokument",
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="podmiot",
        ),
    ]
