# Generated by Django 5.2.1 on 2025-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0005_relacjaprawna_przedawnione"),
    ]

    operations = [
        migrations.AddField(
            model_name="podmiot",
            name="aktualne",
            field=models.BooleanField(default=True, verbose_name="Aktualne"),
        ),
    ]
