# Generated by Django 5.2.1 on 2025-08-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0005_alter_relacjaprawna_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DlugoscKadencji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "okres",
                    models.CharField(
                        max_length=255,
                        verbose_name="Długość okresu urzędowania",
                    ),
                ),
            ],
            options={
                "verbose_name": "Długość kadencji",
                "verbose_name_plural": "Długości kadencji",
                "ordering": ["okres"],
            },
        ),
        migrations.AlterModelOptions(
            name="prawoobowiazek",
            options={
                "ordering": ["podmiot", "relacja"],
                "verbose_name": "Prawo/Obowiązek",
                "verbose_name_plural": "Kodeks",
            },
        ),
    ]
