# Generated by Django 5.2.1 on 2025-08-31 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0006_dlugosckadencji_alter_prawoobowiazek_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WielkoscStruktury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wielkosc", models.CharField(max_length=255, verbose_name="Wielkość")),
            ],
            options={
                "verbose_name": "Wielkosc",
                "verbose_name_plural": "Wielkosc",
                "ordering": ["wielkosc"],
            },
        ),
        migrations.AddField(
            model_name="podmiot",
            name="dlugosc_kadencji",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prawo.dlugosckadencji",
                verbose_name="Długość kadencji",
            ),
        ),
        migrations.AlterField(
            model_name="dlugosckadencji",
            name="okres",
            field=models.CharField(max_length=255, verbose_name="Długość kadencji"),
        ),
    ]
