# Generated by Django 5.2.1 on 2025-08-31 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0007_wielkoscstruktury_podmiot_dlugosc_kadencji_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="struktura",
            name="wielkosc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prawo.wielkoscstruktury",
                verbose_name="Wielkość",
            ),
        ),
    ]
