# Generated by Django 5.2.1 on 2025-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0008_struktura_wielkosc"),
    ]

    operations = [
        migrations.AddField(
            model_name="podmiot",
            name="opis",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
    ]
