# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0013_dlugosckadencji_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dlugosckadencji",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="dlugosckadencji",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="prawoobowiazek",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="prawoobowiazek",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="rola",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="rola",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="struktura",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="struktura",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="wielkoscstruktury",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="wielkoscstruktury",
            name="search_dict",
        ),
    ]
