# Generated by Django 5.2.1 on 2025-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0014_remove_dlugosckadencji_fields_positions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dlugosckadencji",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="prawoobowiazek",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="relacjaprawna",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="rola",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="struktura",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="wielkoscstruktury",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
