# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0015_dlugosckadencji_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dlugosckadencji",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="prawoobowiazek",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="relacjaprawna",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="rola",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="struktura",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="wielkoscstruktury",
            name="search_text",
        ),
    ]
