# Generated by Django 5.2.1 on 2025-09-12 13:55

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0017_remove_rola_search_dict_remove_rola_tsv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dlugosckadencji",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="podmiot",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="prawoobowiazek",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="relacjaprawna",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="wielkoscstruktury",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
