# Generated by Django 5.2.1 on 2025-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0018_dlugosckadencji_simple_tsv_podmiot_simple_tsv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dlugosckadencji",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="podmiot",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="prawoobowiazek",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="relacjaprawna",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="wielkoscstruktury",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
