# Generated by Django 5.2.1 on 2025-12-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prawo", "0019_alter_dlugosckadencji_search_dict_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wielkoscstruktury",
            options={
                "ordering": ["wielkosc"],
                "verbose_name": "Wielkość",
                "verbose_name_plural": "Wielkości",
            },
        ),
    ]
