# Generated by Django 5.2.1 on 2025-07-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0002_zwrot_cosik_zwrot_wtf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zwrot",
            options={
                "ordering": ["wtf"],
                "verbose_name": "Zwrot",
                "verbose_name_plural": "Zwroty",
            },
        ),
        migrations.RemoveField(
            model_name="zwrot",
            name="tlumaczenie",
        ),
        migrations.RemoveField(
            model_name="zwrot",
            name="zwrot",
        ),
    ]
