# Generated by Django 5.2.1 on 2025-07-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0004_zwrot_tlumaczenie_zwrot_zwrot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zwrot",
            options={
                "ordering": ["zwrot"],
                "verbose_name": "Zwrot",
                "verbose_name_plural": "Zwroty",
            },
        ),
        migrations.RemoveField(
            model_name="zwrot",
            name="cosik",
        ),
        migrations.RemoveField(
            model_name="zwrot",
            name="wtf",
        ),
    ]
