# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0005_alter_zwrot_options_remove_zwrot_cosik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zwrot",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
