# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0006_zwrot_search_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="zwrot",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
