# Generated by Django 5.2.1 on 2025-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0008_zwrot_tsv"),
    ]

    operations = [
        migrations.AddField(
            model_name="zwrot",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
