# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0009_zwrot_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zwrot",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="zwrot",
            name="search_dict",
        ),
    ]
