# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0011_zwrot_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zwrot",
            name="search_text",
        ),
    ]
