# Generated by Django 5.2.1 on 2025-09-12 13:55

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slowniczek_lacinski", "0012_remove_zwrot_search_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="zwrot",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
