# Generated by Django 5.2.1 on 2025-07-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kraj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kraj",
                    models.CharField(max_length=100, verbose_name="Kraj"),
                ),
            ],
            options={
                "verbose_name": "Kraj",
                "verbose_name_plural": "Kraje",
                "ordering": ["kraj"],
            },
        ),
        migrations.CreateModel(
            name="Uczelnia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=255, verbose_name="Uczelnia"),
                ),
                (
                    "akronim",
                    models.CharField(max_length=10, verbose_name="Akronim"),
                ),
                (
                    "kraj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="miejsca.kraj",
                        verbose_name="Kraj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uczelnia",
                "verbose_name_plural": "Uczelnie",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Wydzial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Wydział"
                    ),
                ),
                (
                    "skrot",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Skrót"
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="miejsca.uczelnia",
                        verbose_name="Uczelnia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydział",
                "verbose_name_plural": "Wydziały",
                "ordering": ["uczelnia", "nazwa"],
            },
        ),
    ]
