# Generated by Django 5.2.1 on 2025-07-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miejsca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uczelnia',
            options={'ordering': ['kraj', 'nazwa'], 'verbose_name': 'Uczelnia', 'verbose_name_plural': 'Uczelnie'},
        ),
    ]
