# Generated by Django 5.2.1 on 2025-07-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0002_alter_uczelnia_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypMiejsca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        max_length=100, verbose_name="Typ miejsca"
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ miejsca",
                "verbose_name_plural": "Typy miejsc",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Miejsce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=255, verbose_name="Nazwa"),
                ),
                (
                    "adres",
                    models.CharField(
                        blank=True,
                        default="Ulica 1, Kraków, Polska",
                        max_length=255,
                        verbose_name="Adres",
                    ),
                ),
                (
                    "typ",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="miejsca.typmiejsca",
                        verbose_name="Typ miejsca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miejsce",
                "verbose_name_plural": "Miejsca",
                "ordering": ["nazwa"],
            },
        ),
    ]
