# Generated by Django 5.2.1 on 2025-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miejsca', '0003_typmiejsca_miejsce'),
    ]

    operations = [
        migrations.AddField(
            model_name='miejsce',
            name='zamkniete_na_stale',
            field=models.BooleanField(default=False, verbose_name='Zamknięte na stałe'),
        ),
        migrations.AlterField(
            model_name='miejsce',
            name='adres',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adres'),
        ),
    ]
