# Generated by Django 5.2.1 on 2025-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miejsce",
            name="adres",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Adres (wystarczy skopiować z Googla)",
            ),
        ),
    ]
