# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0005_alter_miejsce_adres"),
    ]

    operations = [
        migrations.AddField(
            model_name="kraj",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="miejsce",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="typmiejsca",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="wydzial",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
