# Generated by Django 5.2.1 on 2025-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0008_kraj_tsv_miejsce_tsv_typmiejsca_tsv_uczelnia_tsv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kraj",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="miejsce",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="typmiejsca",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="wydzial",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
