# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0009_kraj_search_dict_miejsce_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kraj",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="kraj",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="miejsce",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="miejsce",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="typmiejsca",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="typmiejsca",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="uczelnia",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="uczelnia",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="wydzial",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="wydzial",
            name="search_dict",
        ),
    ]
