# Generated by Django 5.2.1 on 2025-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0013_kraj_simple_tsv_miejsce_simple_tsv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miejsce",
            name="latitude",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="miejsce",
            name="longitude",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
