# Generated by Django 5.2.1 on 2025-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0014_miejsce_latitude_miejsce_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="miejsce",
            name="niestandardowy_adres",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Adres niestandardowy",
            ),
        ),
    ]
