# Generated by Django 5.2.1 on 2025-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0015_miejsce_niestandardowy_adres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miejsce",
            name="adres",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Adres (wystarczy skopiować z Googla)",
            ),
        ),
        migrations.AlterField(
            model_name="miejsce",
            name="niestandardowy_adres",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Adres niestandardowy (niezrozumiały dla map)",
            ),
        ),
    ]
