# Generated by Django 5.2.1 on 2025-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0016_alter_miejsce_adres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="typmiejsca",
            name="emoji",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Emoji"
            ),
        ),
    ]
