# Generated by Django 5.2.1 on 2025-10-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miejsca", "0018_alter_kraj_search_dict_alter_miejsce_search_dict_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miejsce",
            name="adres",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Adres (wystarczy skopiować z Googla i dodać kraj)",
            ),
        ),
    ]
