# Generated by Django 5.2 on 2025-05-01 12:51

import czlonkowie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_kadencja_zakonczenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czapka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uczelnia', models.CharField(choices=[('UJ', 'UJ'), ('AGH', 'AGH'), ('PK', 'PK'), ('UEK', 'UEK'), ('UW', 'UW'), ('UŚ', 'UŚ'), ('UŁ', 'UŁ'), ('UP_L', 'Uniwersytet Przyrodniczy w Lublinie'), ('NIEMCY', 'Niemcy'), ('XXX', 'Nie wiem'), ('n/a', 'Nie dotyczy')], default='UJ', max_length=10, verbose_name='Uczelnia')),
                ('wydzial', models.CharField(default=('XXX', 'Nie wiem'), max_length=10, verbose_name='Wydział')),
                ('kolor', models.CharField(default='', max_length=255, verbose_name='Kolor')),
            ],
            options={
                'verbose_name': 'Czapka',
                'verbose_name_plural': 'Czapki',
                'ordering': ['uczelnia', 'kolor', 'wydzial'],
            },
        ),
        migrations.CreateModel(
            name='Czlonek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40, verbose_name='Imię')),
                ('nazwisko', models.CharField(blank=True, max_length=40, verbose_name='Nazwisko')),
                ('aktywnosc', models.CharField(choices=[('A', 'Aktywny'), ('M', 'Aktywny tylko w mediach'), ('N', 'Nieaktywny'), ('O', 'Odszedł z grupy')], default='N', max_length=1, verbose_name='Aktywność')),
                ('ochrzczony', models.CharField(choices=[('T', 'Tak'), ('N', 'Nie'), ('d/n', 'Nie wiem')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Ochrzczony?')),
                ('rok_chrztu', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'Nie wiem'), verbose_name='Rok chrztu')),
                ('miesiac_chrztu', models.IntegerField(choices=[(1, 'styczeń'), (2, 'luty'), (3, 'marzec'), (4, 'kwiecień'), (5, 'maj'), (6, 'czerwiec'), (7, 'lipiec'), (8, 'sierpień'), (9, 'wrzesień'), (10, 'październik'), (11, 'listopad'), (12, 'grudzień'), (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'Nie wiem'), verbose_name='Miesiąc chrztu')),
                ('dzien_chrztu', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'Nie wiem'), verbose_name='Dzień chrztu')),
                ('staz', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem')], default=(1111111111, 'Nie wiem'), verbose_name='Rok pojawienia się')),
                ('pewnosc_stazu', models.BooleanField(choices=[(True, 'Na pewno wcześniej się nie pojawiał'), (False, 'Ale mógł pojawić się wcześniej')], default=(False, 'Ale mógł pojawić się wcześniej'), verbose_name='Pewność daty stażu')),
                ('status', models.CharField(choices=[('B', 'Bean'), ('C', 'Członek'), ('X', 'Wydalony (np. "Jezus")'), ('W', 'Weteran'), ('H', 'Członek Honoris Causa'), ('d/n', 'Nie wiem')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Status')),
                ('imie_piwne_1_wybor', models.CharField(choices=[('d/n', 'Nie wiem'), ('n/a', 'Nie dotyczy'), ('other', 'Posiada')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Imię czapkowe')),
                ('imie_piwne_1', models.CharField(default='Nie wiem', max_length=100, verbose_name='Wpisz imię czapkowe:')),
                ('imie_piwne_2_wybor', models.CharField(choices=[('n/a', 'Nie dotyczy'), ('other', 'Posiada')], default=('n/a', 'Nie dotyczy'), max_length=5, verbose_name='Inne imię czapkowe')),
                ('imie_piwne_2', models.CharField(default='Nie dotyczy', max_length=100, verbose_name='Wpisz inne imię czapkowe:')),
                ('czapka_1', models.ForeignKey(default=czlonkowie.models.Czapka.get_dont_know_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czapka_1', to='czlonkowie.czapka', verbose_name='Czapka')),
                ('czapka_2', models.ForeignKey(default=czlonkowie.models.Czapka.get_not_applicable_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czapka_2', to='czlonkowie.czapka', verbose_name='Inna czapka')),
                ('rodzic_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodzic_1_set', to='czlonkowie.czlonek', verbose_name='Rodzic czapkowy')),
                ('rodzic_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodzic_2_set', to='czlonkowie.czlonek', verbose_name='Drugi rodzic czapkowy')),
            ],
            options={
                'verbose_name': 'Członek',
                'verbose_name_plural': 'Członkowie',
                'ordering': ['imie', 'imie_piwne_1', 'imie_piwne_2', 'nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='DawnyZarzad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibendi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_bibendi', to='czlonkowie.czlonek', verbose_name='Bibendi')),
                ('cantandi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_cantandi', to='czlonkowie.czlonek', verbose_name='Cantandi')),
                ('kadencja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kadencja', verbose_name='Kadencja')),
                ('kasztelan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_kasztelan', to='czlonkowie.czlonek', verbose_name='Kasztelan')),
                ('kontakt_z_SKNHI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_kontakt_z_SKNHI', to='czlonkowie.czlonek', verbose_name='Kontakt Z SKNHI')),
                ('kontakt_z_SSUJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_kontakt_z_SSUJ', to='czlonkowie.czlonek', verbose_name='Kontakt Z SSUJ')),
                ('magister_disciplinae', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_magister_disciplinae', to='czlonkowie.czlonek', verbose_name='Magister Disciplinae')),
                ('skarbnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_skarbnik', to='czlonkowie.czlonek', verbose_name='Skarbnik')),
                ('wielki_mistrz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dz_wielki_mistrz', to='czlonkowie.czlonek', verbose_name='Wielki Mistrz')),
            ],
            options={
                'verbose_name': 'Dawny Zarząd',
                'verbose_name_plural': 'Dawne Zarządy',
                'ordering': ['-kadencja'],
            },
        ),
        migrations.CreateModel(
            name='ImieSzlacheckie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='czlonkowie.czlonek', verbose_name='Imię szlacheckie')),
            ],
            options={
                'verbose_name': 'Imię szlacheckie',
                'verbose_name_plural': 'Imiona szlacheckie',
                'ordering': ['imie__imie_piwne_1', 'imie__imie', 'imie__nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='ZwierzeCzapkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwierze', models.CharField(max_length=100, verbose_name='Zwierzę')),
                ('wyjasnienie', models.CharField(blank=True, max_length=100, verbose_name='Wyjaśnienie (opcjonalne)')),
                ('czlonek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Członek')),
            ],
            options={
                'verbose_name': 'Zwierzę czapkowe',
                'verbose_name_plural': 'Zwierzęta czapkowe',
                'ordering': ['zwierze', 'czlonek__imie_piwne_1'],
            },
        ),
    ]
