# Generated by Django 5.2.1 on 2025-05-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('czlonkowie', '0001_initial'),
        ('encyklopedia', '0002_tradycjabcs_wydarzenie'),
    ]

    operations = [
    ]
