# Generated by Django 5.2 on 2025-05-01 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_kadencja_zakonczenie'),
        ('czlonkowie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WielkiMistrz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tadeusz', models.CharField(max_length=10, verbose_name='Tadeusz')),
                ('tytuly', models.TextField(blank=True, verbose_name='Tytuły')),
                ('imie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Imię')),
                ('kadencja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kadencja', verbose_name='Kadencja')),
            ],
            options={
                'verbose_name': 'Wielki Mistrz',
                'verbose_name_plural': 'Wielcy Mistrzowie',
                'ordering': ['-kadencja'],
            },
        ),
        migrations.CreateModel(
            name='Zarzad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantandi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cantandi', to='czlonkowie.czlonek', verbose_name='Cantandi')),
                ('kadencja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kadencja', verbose_name='Kadencja')),
                ('kasztelan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kasztelan', to='czlonkowie.czlonek', verbose_name='Kasztelan')),
                ('sekretarz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekretarz', to='czlonkowie.czlonek', verbose_name='Sekretarz')),
                ('skarbnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skarbnik', to='czlonkowie.czlonek', verbose_name='Skarbnik')),
                ('wielki_mistrz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wielki_mistrz', to='czlonkowie.czlonek', verbose_name='Wielki Mistrz')),
            ],
            options={
                'verbose_name': 'Zarząd',
                'verbose_name_plural': 'Zarządy',
                'ordering': ['-kadencja'],
            },
        ),
    ]
