# Generated by Django 5.2 on 2025-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0002_wielkimistrz_zarzad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czapka',
            name='uczelnia',
            field=models.CharField(choices=[('UJ', 'UJ'), ('AGH', 'AGH'), ('PK', 'PK'), ('UEK', 'UEK'), ('UW', 'UW'), ('UŚ', 'UŚ'), ('UŁ', 'UŁ'), ('UP_L', 'Uniwersytet Przyrodniczy w Lublinie'), ('NIEMCY', 'Niemcy'), ('XXX', 'ZMIENILEM'), ('n/a', 'Nie dotyczy')], default='UJ', max_length=10, verbose_name='Uczelnia'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='dzien_chrztu',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (1111111111, 'ZMIENILEM'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'ZMIENILEM'), verbose_name='Dzień chrztu'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='imie_piwne_1_wybor',
            field=models.CharField(choices=[('d/n', 'ZMIENILEM'), ('n/a', 'Nie dotyczy'), ('other', 'Posiada')], default=('d/n', 'ZMIENILEM'), max_length=5, verbose_name='Imię czapkowe'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='miesiac_chrztu',
            field=models.IntegerField(choices=[(1, 'styczeń'), (2, 'luty'), (3, 'marzec'), (4, 'kwiecień'), (5, 'maj'), (6, 'czerwiec'), (7, 'lipiec'), (8, 'sierpień'), (9, 'wrzesień'), (10, 'październik'), (11, 'listopad'), (12, 'grudzień'), (1111111111, 'ZMIENILEM'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'ZMIENILEM'), verbose_name='Miesiąc chrztu'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='ochrzczony',
            field=models.CharField(choices=[('T', 'Tak'), ('N', 'Nie'), ('d/n', 'ZMIENILEM')], default=('d/n', 'ZMIENILEM'), max_length=5, verbose_name='Ochrzczony?'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='rok_chrztu',
            field=models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'ZMIENILEM'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'ZMIENILEM'), verbose_name='Rok chrztu'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='status',
            field=models.CharField(choices=[('B', 'Bean'), ('C', 'Członek'), ('X', 'Wydalony (np. "Jezus")'), ('W', 'Weteran'), ('H', 'Członek Honoris Causa'), ('d/n', 'ZMIENILEM')], default=('d/n', 'ZMIENILEM'), max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='staz',
            field=models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'ZMIENILEM')], default=(1111111111, 'ZMIENILEM'), verbose_name='Rok pojawienia się'),
        ),
    ]
