# Generated by Django 5.2 on 2025-05-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0004_alter_czapka_uczelnia_alter_czlonek_dzien_chrztu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wielkimistrz',
            options={'ordering': ['-tadeusz'], 'verbose_name': 'Wielki Mistrz', 'verbose_name_plural': 'Wielcy Mistrzowie'},
        ),
        migrations.RemoveField(
            model_name='wielkimistrz',
            name='kadencja',
        ),
    ]
