# Generated by Django 5.2 on 2025-05-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0005_alter_wielkimistrz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wielkimistrz',
            options={'verbose_name': 'Wielki Mistrz', 'verbose_name_plural': 'Wielcy Mistrzowie'},
        ),
    ]
