# Generated by Django 5.2.1 on 2025-07-19 10:25

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def migrate_old_to_new(apps, schema_editor):
    # Get models
    Czlonek = apps.get_model('czlonkowie', 'Czlonek')
    OldCzlonek = apps.get_model('czlonkowie', 'OldCzlonek')

    # STEP 1: Migrate Czlonek (ID-preserving)
    for old in OldCzlonek.objects.all():
        new = Czlonek(
            id=old.id,  # Required: preserve ID for FK relations
            imie=old.imie,
            nazwisko=old.nazwisko,
            przezwiska=old.przezwiska,
            staz=old.staz,
            pewnosc_stazu=old.pewnosc_stazu,
            czapka_1=old.czapka_1,
            czapka_2=old.czapka_2,
            aktywnosc=old.aktywnosc,
            ochrzczony=old.ochrzczony,
            rok_chrztu=old.rok_chrztu,
            miesiac_chrztu=old.miesiac_chrztu,
            dzien_chrztu=old.dzien_chrztu,
            status=old.status,
            imie_piwne_1_wybor=old.imie_piwne_1_wybor,
            imie_piwne_1=old.imie_piwne_1,
            imie_piwne_2_wybor=old.imie_piwne_2_wybor,
            imie_piwne_2=old.imie_piwne_2,
        )
        new.save()

    # STEP 2: Assign rodzic_1, rodzic_2
    for old in OldCzlonek.objects.all():
        new = Czlonek.objects.get(id=old.id)
        new.rodzic_1_id = old.rodzic_1_id
        new.rodzic_2_id = old.rodzic_2_id
        new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0005_osoba_alter_oldbean_rodzic_1_alter_oldbean_rodzic_2_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_old_to_new)
    ]
