# Generated by Django 5.2 on 2025-05-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0006_alter_wielkimistrz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wielkimistrz',
            options={'ordering': ['-tadeusz_numeric'], 'verbose_name': 'Wielki Mistrz', 'verbose_name_plural': 'Wielcy Mistrzowie'},
        ),
        migrations.AddField(
            model_name='wielkimistrz',
            name='tadeusz_numeric',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
