# Generated by Django 5.2 on 2025-05-02 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0007_alter_wielkimistrz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podziekowania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaslugi', models.CharField(max_length=255, verbose_name='Zasługi')),
                ('edited', models.DateTimeField(auto_now=True)),
                ('czlonek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Członek')),
            ],
            options={
                'verbose_name': 'Podziękowania',
                'verbose_name_plural': 'Podziękowania',
                'ordering': ['-edited'],
            },
        ),
    ]
