# Generated by Django 5.2 on 2025-05-02 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0008_podziekowania'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_alternatywna', models.CharField(blank=True, max_length=100, verbose_name='Nazwa alternatywna')),
                ('zaslugi', models.CharField(max_length=255, verbose_name='Zasługi')),
                ('edited', models.DateTimeField(auto_now=True)),
                ('czlonek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Członek')),
            ],
            options={
                'verbose_name': 'Hall of Fame',
                'verbose_name_plural': 'Hall of Fame',
                'ordering': ['-edited'],
            },
        ),
        migrations.DeleteModel(
            name='Podziekowania',
        ),
    ]
