# Generated by Django 5.2 on 2025-05-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0009_halloffame_delete_podziekowania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halloffame',
            options={'ordering': ['numer'], 'verbose_name': 'Hall of Fame', 'verbose_name_plural': 'Hall of Fame'},
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='edited',
        ),
        migrations.AddField(
            model_name='halloffame',
            name='numer',
            field=models.IntegerField(default=0, verbose_name='Numer'),
            preserve_default=False,
        ),
    ]
