# Generated by Django 5.2 on 2025-05-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0010_alter_halloffame_options_remove_halloffame_edited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halloffame',
            options={'ordering': ['czlonek', 'nazwa_alternatywna'], 'verbose_name': 'Hall of Fame', 'verbose_name_plural': 'Hall of Fame'},
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='numer',
        ),
    ]
