# Generated by Django 5.2 on 2025-05-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0011_alter_halloffame_options_remove_halloffame_numer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halloffame',
            options={'verbose_name': 'Hall of Fame', 'verbose_name_plural': 'Hall of Fame'},
        ),
    ]
