# Generated by Django 5.2 on 2025-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0012_alter_halloffame_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halloffame',
            options={'ordering': ['order_field'], 'verbose_name': 'Hall of Fame', 'verbose_name_plural': 'Hall of Fame'},
        ),
        migrations.AddField(
            model_name='halloffame',
            name='order_field',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
