# Generated by Django 5.2 on 2025-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0013_alter_halloffame_options_halloffame_order_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnaOsoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imie i nazwisko')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Inna osoba',
                'verbose_name_plural': 'Inne osoby (nie-członkowie)',
                'ordering': ['imie'],
            },
        ),
    ]
