# Generated by Django 5.2 on 2025-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0014_innaosoba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innaosoba',
            options={'ordering': ['nazwa'], 'verbose_name': 'Inna osoba', 'verbose_name_plural': 'Inne osoby (nie-członkowie)'},
        ),
        migrations.RemoveField(
            model_name='innaosoba',
            name='imie',
        ),
        migrations.AddField(
            model_name='innaosoba',
            name='kategoria',
            field=models.CharField(choices=[('I', 'Inna'), ('Inne BCS', 'Inne bractwo czapkowe'), ('Org', 'Organizacja'), ('PC', 'Przyjaciel Bractwa')], default='I', max_length=10, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='innaosoba',
            name='nazwa',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwa'),
            preserve_default=False,
        ),
    ]
