# Generated by Django 5.2 on 2025-05-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0015_alter_innaosoba_options_remove_innaosoba_imie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przezwisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przezwisko', models.CharField(max_length=255, verbose_name='Przezwisko')),
                ('kto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czlonkowie.czlonek', verbose_name='Kto')),
            ],
            options={
                'verbose_name': 'Przezwisko',
                'verbose_name_plural': 'Przezwiska',
                'ordering': ['kto', 'przezwisko'],
            },
        ),
    ]
