# Generated by Django 5.2 on 2025-05-13 10:42

import czlonkowie.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0016_przezwisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonek',
            name='czapka_1',
            field=models.ForeignKey(default=czlonkowie.models.Czapka.get_dont_know_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czlonek_czapka_1', to='czlonkowie.czapka', verbose_name='Czapka'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='czapka_2',
            field=models.ForeignKey(default=czlonkowie.models.Czapka.get_not_applicable_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czlonek_czapka_2', to='czlonkowie.czapka', verbose_name='Inna czapka'),
        ),
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40, verbose_name='Imię')),
                ('nazwisko', models.CharField(blank=True, max_length=40, verbose_name='Nazwisko')),
                ('staz', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem')], default=(1111111111, 'Nie wiem'), verbose_name='Rok pojawienia się')),
                ('pewnosc_stazu', models.BooleanField(choices=[(True, 'Na pewno wcześniej się nie pojawiał'), (False, 'Ale mógł pojawić się wcześniej')], default=(False, 'Ale mógł pojawić się wcześniej'), verbose_name='Pewność daty stażu')),
                ('czapka_1', models.ForeignKey(default=czlonkowie.models.Czapka.get_dont_know_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bean_czapka_1', to='czlonkowie.czapka', verbose_name='Czapka')),
                ('czapka_2', models.ForeignKey(default=czlonkowie.models.Czapka.get_not_applicable_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bean_czapka_2', to='czlonkowie.czapka', verbose_name='Inna czapka')),
                ('rodzic_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodzic_1_set', to='czlonkowie.bean', verbose_name='Rodzic czapkowy')),
                ('rodzic_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodzic_2_set', to='czlonkowie.bean', verbose_name='Drugi rodzic czapkowy')),
            ],
            options={
                'verbose_name': 'Bean',
                'verbose_name_plural': 'Beani',
                'ordering': ['imie', 'nazwisko'],
            },
        ),
    ]
