# Generated by Django 5.2 on 2025-05-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0017_alter_czlonek_czapka_1_alter_czlonek_czapka_2_bean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='rodzic_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bean_rodzic_1_set', to='czlonkowie.czlonek', verbose_name='Rodzic czapkowy'),
        ),
        migrations.AlterField(
            model_name='bean',
            name='rodzic_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bean_rodzic_2_set', to='czlonkowie.czlonek', verbose_name='Drugi rodzic czapkowy'),
        ),
    ]
