# Generated by Django 5.2 on 2025-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0018_alter_bean_rodzic_1_alter_bean_rodzic_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='pewnosc_stazu',
            field=models.BooleanField(choices=[(True, 'Na pewno wcześniej się nie pojawiał'), (False, 'Ale mógł pojawić się wcześniej')], default=(True, 'Na pewno wcześniej się nie pojawiał'), verbose_name='Pewność daty stażu'),
        ),
        migrations.AlterField(
            model_name='bean',
            name='staz',
            field=models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem')], default=2024, verbose_name='Rok pojawienia się'),
        ),
    ]
