# Generated by Django 5.2 on 2025-05-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0019_alter_bean_pewnosc_stazu_alter_bean_staz'),
        ('encyklopedia', '0009_alter_bractwo_rok_zalozenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='innaosoba',
            name='bractwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyklopedia.bractwo', verbose_name='Bractwo'),
        ),
    ]
