# Generated by Django 5.2.1 on 2025-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0002_innaosoba_bractwo_przezwisko_kto_wielkimistrz_imie_and_more'),
        ('czlonkowie', '0020_innaosoba_bractwo'),
    ]

    operations = [
    ]
