# Generated by Django 5.2.1 on 2025-05-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0022_osoby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czapka',
            name='wydzial',
            field=models.CharField(default='XXX', max_length=10, verbose_name='Wydział'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='pewnosc_stazu',
            field=models.CharField(choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')], default='N', verbose_name='Pewność daty stażu'),
        ),
    ]
