# Generated by Django 5.2.1 on 2025-05-15 00:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0024_alter_bean_czapka_1_alter_bean_czapka_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='czlonek',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
