# Generated by Django 5.2.1 on 2025-05-15 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0025_bean_przezwiska_czlonek_przezwiska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Przezwiska'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Przezwiska'),
        ),
    ]
