# Generated by Django 5.2.1 on 2025-05-15 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0026_alter_bean_przezwiska_alter_czlonek_przezwiska'),
    ]

    operations = [
        migrations.AddField(
            model_name='innaosoba',
            name='imie',
            field=models.CharField(default='', verbose_name='Imię'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innaosoba',
            name='nazwisko',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AddField(
            model_name='innaosoba',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Przezwiska'),
        ),
    ]
