# Generated by Django 5.2.1 on 2025-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0027_innaosoba_imie_innaosoba_nazwisko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innaosoba',
            name='nazwisko',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nazwisko'),
            preserve_default=False,
        ),
    ]
