# Generated by Django 5.2.1 on 2025-05-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0028_alter_innaosoba_nazwisko'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innaosoba',
            options={'ordering': ['imie', 'nazwisko'], 'verbose_name': 'Inna osoba', 'verbose_name_plural': 'Inne osoby (nie-członkowie)'},
        ),
        migrations.RemoveField(
            model_name='innaosoba',
            name='nazwa',
        ),
    ]
