# Generated by Django 5.2.1 on 2025-05-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0029_alter_innaosoba_options_remove_innaosoba_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innaosoba',
            name='imie',
            field=models.CharField(max_length=40, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='innaosoba',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nazwisko'),
        ),
    ]
