# Generated by Django 5.2.1 on 2025-05-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0030_alter_innaosoba_imie_alter_innaosoba_nazwisko'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Przezwisko',
        ),
    ]
