# Generated by Django 5.2.1 on 2025-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0031_delete_przezwisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bean',
            name='pewnosc_stazu',
            field=models.CharField(choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')], default='T', verbose_name='Pewność daty stażu'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='pewnosc_stazu',
            field=models.CharField(choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')], default='T', verbose_name='Pewność daty stażu'),
        ),
    ]
