# Generated by Django 5.2.1 on 2025-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0032_alter_bean_pewnosc_stazu_alter_czlonek_pewnosc_stazu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonek',
            name='imie_piwne_1_wybor',
            field=models.CharField(choices=[('n/a', 'Nie dotyczy'), ('d/n', 'Nie wiem'), ('other', 'Posiada')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Imię czapkowe'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='imie_piwne_2_wybor',
            field=models.CharField(choices=[('n/a', 'Nie dotyczy'), ('d/n', 'Nie wiem'), ('other', 'Posiada')], default=('n/a', 'Nie dotyczy'), max_length=5, verbose_name='Inne imię czapkowe'),
        ),
    ]
