# Generated by Django 5.2.1 on 2025-05-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0033_alter_czlonek_imie_piwne_1_wybor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='bean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.bean', verbose_name='Bean'),
        ),
        migrations.AlterField(
            model_name='czlonek',
            name='status',
            field=models.CharField(choices=[('C', 'Członek'), ('X', 'Wydalony (np. "Jezus")'), ('W', 'Weteran'), ('H', 'Członek Honoris Causa'), ('d/n', 'Nie wiem')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Status'),
        ),
    ]
