# Generated by Django 5.2.1 on 2025-07-17 14:44

import osoby.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czapka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uczelnia', models.CharField(choices=[('UJ', 'UJ'), ('AGH', 'AGH'), ('PK', 'PK'), ('UEK', 'UEK'), ('WSE', 'WSE (teraz USWPS)'), ('UW', 'UW'), ('UŚ', 'UŚ'), ('UŁ', 'UŁ'), ('UP_L', 'Uniwersytet Przyrodniczy w Lublinie'), ('NIEMCY', 'Niemcy'), ('XXX', 'Nie wiem'), ('n/a', 'Nie dotyczy')], default='UJ', max_length=10, verbose_name='Uczelnia')),
                ('wydzial', models.CharField(default='XXX', max_length=10, verbose_name='Wydział')),
                ('kolor', models.CharField(default='', max_length=255, verbose_name='Kolor')),
            ],
            options={
                'verbose_name': 'Czapka',
                'verbose_name_plural': 'Czapki',
                'ordering': ['uczelnia', 'kolor', 'wydzial'],
            },
        ),
        migrations.CreateModel(
            name='InnaOsoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40, verbose_name='Imię')),
                ('nazwisko', models.CharField(blank=True, max_length=40, verbose_name='Nazwisko')),
                ('przezwiska', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Przezwiska')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('kategoria', models.CharField(choices=[('I', 'Inna'), ('Inne BCS', 'Inne bractwo czapkowe'), ('Org', 'Organizacja'), ('PC', 'Przyjaciel Bractwa')], default='I', max_length=10, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Inna osoba',
                'verbose_name_plural': 'Inne osoby (nie-członkowie)',
                'ordering': ['imie', 'nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='Osoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
            },
        ),
        migrations.CreateModel(
            name='WielkiMistrz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tadeusz', models.CharField(max_length=10, verbose_name='Tadeusz')),
                ('tadeusz_numeric', models.IntegerField(db_index=True, default=0, editable=False)),
                ('tytuly', models.TextField(blank=True, verbose_name='Tytuły')),
            ],
            options={
                'verbose_name': 'Wielki Mistrz',
                'verbose_name_plural': 'Wielcy Mistrzowie',
                'ordering': ['-tadeusz_numeric'],
            },
        ),
        migrations.CreateModel(
            name='Zarzad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Zarząd',
                'verbose_name_plural': 'Zarządy',
            },
        ),
        migrations.CreateModel(
            name='Czlonek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40, verbose_name='Imię')),
                ('nazwisko', models.CharField(blank=True, max_length=40, verbose_name='Nazwisko')),
                ('przezwiska', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Przezwiska')),
                ('staz', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem')], default=2024, verbose_name='Rok pojawienia się')),
                ('pewnosc_stazu', models.CharField(choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')], default='T', verbose_name='Pewność daty stażu')),
                ('aktywnosc', models.CharField(choices=[('A', 'Aktywny'), ('M', 'Aktywny tylko w mediach'), ('N', 'Nieaktywny'), ('O', 'Odszedł z grupy')], default='N', max_length=1, verbose_name='Aktywność')),
                ('ochrzczony', models.CharField(choices=[('T', 'Tak'), ('N', 'Nie'), ('d/n', 'Nie wiem')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Ochrzczony?')),
                ('rok_chrztu', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'Nie wiem'), verbose_name='Rok chrztu')),
                ('miesiac_chrztu', models.IntegerField(choices=[(1, 'styczeń'), (2, 'luty'), (3, 'marzec'), (4, 'kwiecień'), (5, 'maj'), (6, 'czerwiec'), (7, 'lipiec'), (8, 'sierpień'), (9, 'wrzesień'), (10, 'październik'), (11, 'listopad'), (12, 'grudzień'), (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'Nie wiem'), verbose_name='Miesiąc chrztu')),
                ('dzien_chrztu', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')], default=(1111111111, 'Nie wiem'), verbose_name='Dzień chrztu')),
                ('status', models.CharField(choices=[('C', 'Członek'), ('X', 'Wydalony (np. "Jezus")'), ('W', 'Weteran'), ('H', 'Członek Honoris Causa'), ('d/n', 'Nie wiem')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Status')),
                ('imie_piwne_1_wybor', models.CharField(choices=[('n/a', 'Nie dotyczy'), ('d/n', 'Nie wiem'), ('other', 'Posiada')], default=('d/n', 'Nie wiem'), max_length=5, verbose_name='Imię czapkowe')),
                ('imie_piwne_1', models.CharField(blank=True, default='Nie wiem', max_length=100, verbose_name='Wpisz imię czapkowe:')),
                ('imie_piwne_2_wybor', models.CharField(choices=[('n/a', 'Nie dotyczy'), ('d/n', 'Nie wiem'), ('other', 'Posiada')], default=('n/a', 'Nie dotyczy'), max_length=5, verbose_name='Inne imię czapkowe')),
                ('imie_piwne_2', models.CharField(blank=True, default='Nie dotyczy', max_length=100, verbose_name='Wpisz inne imię czapkowe:')),
                ('czapka_1', models.ForeignKey(default=osoby.models.Czapka.get_dont_know_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posiadacze_pierwszy_wybor', to='osoby.czapka', verbose_name='Czapka')),
                ('czapka_2', models.ForeignKey(default=osoby.models.Czapka.get_not_applicable_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posiadacze_drugi_wybor', to='osoby.czapka', verbose_name='Inna czapka')),
                ('rodzic_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dzieci_pierwszy_wybor', to='osoby.czlonek', verbose_name='Rodzic czapkowy')),
                ('rodzic_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dzieci_drugi_wybor', to='osoby.czlonek', verbose_name='Drugi rodzic czapkowy')),
            ],
            options={
                'verbose_name': 'Członek',
                'verbose_name_plural': 'Członkowie',
                'ordering': ['imie', 'imie_piwne_1', 'imie_piwne_2', 'nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40, verbose_name='Imię')),
                ('nazwisko', models.CharField(blank=True, max_length=40, verbose_name='Nazwisko')),
                ('przezwiska', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Przezwiska')),
                ('staz', models.IntegerField(choices=[(2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (1111111111, 'Nie wiem')], default=2024, verbose_name='Rok pojawienia się')),
                ('pewnosc_stazu', models.CharField(choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')], default='T', verbose_name='Pewność daty stażu')),
                ('czapka_1', models.ForeignKey(default=osoby.models.Czapka.get_dont_know_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posiadacze_pierwszy_wybor', to='osoby.czapka', verbose_name='Czapka')),
                ('czapka_2', models.ForeignKey(default=osoby.models.Czapka.get_not_applicable_czapka, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posiadacze_drugi_wybor', to='osoby.czapka', verbose_name='Inna czapka')),
                ('rodzic_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beani_pierwszy_wybor', to='osoby.czlonek', verbose_name='Rodzic czapkowy')),
                ('rodzic_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beani_drugi_wybor', to='osoby.czlonek', verbose_name='Drugi rodzic czapkowy')),
            ],
            options={
                'verbose_name': 'Bean',
                'verbose_name_plural': 'Beani',
                'ordering': ['imie', 'nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='DawnyZarzad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibendi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_bibendi_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Bibendi')),
                ('cantandi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_cantandi_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Cantandi')),
                ('kadencja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kadencja', verbose_name='Kadencja')),
                ('kasztelan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kasztelan_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Kasztelan')),
                ('kontakt_z_SKNHI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kontakt_z_SKNHI_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Kontakt Z SKNHI')),
                ('kontakt_z_SSUJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kontakt_z_SSUJ_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Kontakt Z SSUJ')),
                ('magister_disciplinae', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_magister_disciplinae_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Magister Disciplinae')),
                ('skarbnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_skarbnik_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Skarbnik')),
            ],
            options={
                'verbose_name': 'Dawny Zarząd',
                'verbose_name_plural': 'Dawne Zarządy',
                'ordering': ['-kadencja'],
            },
        ),
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_alternatywna', models.CharField(blank=True, max_length=100, verbose_name='Nazwa alternatywna')),
                ('zaslugi', models.CharField(max_length=255, verbose_name='Zasługi')),
                ('order_field', models.CharField(blank=True, editable=False, max_length=255)),
                ('bean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.bean', verbose_name='Bean')),
                ('czlonek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.czlonek', verbose_name='Członek')),
            ],
            options={
                'verbose_name': 'Hall of Fame',
                'verbose_name_plural': 'Hall of Fame',
                'ordering': ['order_field'],
            },
        ),
        migrations.CreateModel(
            name='ImieSzlacheckie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osoby.czlonek', verbose_name='Imię szlacheckie')),
            ],
            options={
                'verbose_name': 'Imię szlacheckie',
                'verbose_name_plural': 'Imiona szlacheckie',
                'ordering': ['imie__imie_piwne_1', 'imie__imie', 'imie__nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='ZwierzeCzapkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwierze', models.CharField(max_length=100, verbose_name='Zwierzę')),
                ('wyjasnienie', models.CharField(blank=True, max_length=100, verbose_name='Wyjaśnienie (opcjonalne)')),
                ('czlonek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.czlonek', verbose_name='Członek')),
            ],
            options={
                'verbose_name': 'Zwierzę czapkowe',
                'verbose_name_plural': 'Zwierzęta czapkowe',
                'ordering': ['zwierze', 'czlonek__imie_piwne_1'],
            },
        ),
    ]
