# Generated by Django 5.2.1 on 2025-07-18 15:17

import czapki.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czapki', '0004_alter_rodzajczapki_kraje'),
        ('osoby', '0003_alter_czlonek_czapka_1_alter_czlonek_czapka_2_and_more'),
        ('encyklopedia', '0013_alter_pojecie_origins_alter_tradycjabcs_nazwa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Czlonek',
            new_name='OldCzlonek',
        ),
        migrations.RenameModel(
            old_name='Bean',
            new_name='OldBean',
        ),
        migrations.RenameModel(
            old_name='InnaOsoba',
            new_name='InnaOldOsoba',
        ),
        migrations.AlterField(
            model_name='innaoldosoba',
            name='imie',
            field=models.CharField(max_length=40, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='innaoldosoba',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='innaoldosoba',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name='Przezwiska',
            ),
        ),
        migrations.AlterField(
            model_name='innaoldosoba',
            name='opis',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='innaoldosoba',
            name='kategoria',
            field=models.CharField(
                choices=[
                    ('I', 'Inna'),
                    ('Inne BCS', 'Inne bractwo czapkowe'),
                    ('Org', 'Organizacja'),
                    ('PC', 'Przyjaciel Bractwa')
                ],
                default='I',
                max_length=10,
                verbose_name='Kategoria',
            ),
        ),
        migrations.AlterField(
            model_name='innaoldosoba',
            name='bractwo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_czlonkowie_bractwa',
                to='encyklopedia.bractwo',
                verbose_name='Bractwo',
            ),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='imie',
            field=models.CharField(max_length=40, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name='Przezwiska'
            ),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='staz',
            field=models.IntegerField(
                choices=[(y, str(y)) for y in range(2009, 2026)] + [(1111111111, 'Nie wiem')],
                default=2024,
                verbose_name='Rok pojawienia się',
            ),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='pewnosc_stazu',
            field=models.CharField(
                choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')],
                default='T',
                verbose_name='Pewność daty stażu'
            ),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='czapka_1',
            field=models.ForeignKey(
                default=czapki.models.Czapka.get_dont_know_czapka,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_%(class)s_posiadacze_pierwszy_wybor',
                to='czapki.czapka',
                verbose_name='Czapka'
            ),
        ),
        migrations.AlterField(
            model_name='oldbean',
            name='czapka_2',
            field=models.ForeignKey(
                default=czapki.models.Czapka.get_not_applicable_czapka,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_%(class)s_posiadacze_drugi_wybor',
                to='czapki.czapka',
                verbose_name='Inna czapka'
            ),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='bean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.oldbean', verbose_name='Bean'),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='imie',
            field=models.CharField(max_length=40, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='przezwiska',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name='Przezwiska'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='staz',
            field=models.IntegerField(
                choices=[(y, str(y)) for y in range(2009, 2026)] + [(1111111111, 'Nie wiem')],
                default=2024,
                verbose_name='Rok pojawienia się',
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='pewnosc_stazu',
            field=models.CharField(
                choices=[('T', 'Na pewno wcześniej się nie pojawiał'), ('N', 'Ale mógł pojawić się wcześniej')],
                default='T',
                verbose_name='Pewność daty stażu'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='aktywnosc',
            field=models.CharField(
                choices=[('A', 'Aktywny'), ('M', 'Aktywny tylko w mediach'), ('N', 'Nieaktywny'),
                         ('O', 'Odszedł z grupy')],
                default='N',
                max_length=1,
                verbose_name='Aktywność'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='ochrzczony',
            field=models.CharField(
                choices=[('T', 'Tak'), ('N', 'Nie'), ('d/n', 'Nie wiem')],
                default='d/n',
                max_length=5,
                verbose_name='Ochrzczony?'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='rok_chrztu',
            field=models.IntegerField(
                choices=[(y, str(y)) for y in range(2009, 2026)] + [
                    (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')],
                default=1111111111,
                verbose_name='Rok chrztu'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='miesiac_chrztu',
            field=models.IntegerField(
                choices=[
                    (1, 'styczeń'), (2, 'luty'), (3, 'marzec'), (4, 'kwiecień'),
                    (5, 'maj'), (6, 'czerwiec'), (7, 'lipiec'), (8, 'sierpień'),
                    (9, 'wrzesień'), (10, 'październik'), (11, 'listopad'), (12, 'grudzień'),
                    (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')],
                default=1111111111,
                verbose_name='Miesiąc chrztu'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='dzien_chrztu',
            field=models.IntegerField(
                choices=[(i, str(i)) for i in range(1, 32)] + [
                    (1111111111, 'Nie wiem'), (1010101010, 'Nie dotyczy')],
                default=1111111111,
                verbose_name='Dzień chrztu'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='status',
            field=models.CharField(
                choices=[('C', 'Członek'), ('X', 'Wydalony (np. "Jezus")'), ('W', 'Weteran'),
                         ('H', 'Członek Honoris Causa'), ('d/n', 'Nie wiem')],
                default='d/n',
                max_length=5,
                verbose_name='Status'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='imie_piwne_1_wybor',
            field=models.CharField(
                choices=[('n/a', 'Nie dotyczy'), ('d/n', 'Nie wiem'), ('other', 'Posiada')],
                default='d/n',
                max_length=5,
                verbose_name='Imię czapkowe'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='imie_piwne_1',
            field=models.CharField(
                blank=True,
                default='Nie wiem',
                max_length=100,
                verbose_name='Wpisz imię czapkowe:'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='imie_piwne_2_wybor',
            field=models.CharField(
                choices=[('n/a', 'Nie dotyczy'), ('d/n', 'Nie wiem'), ('other', 'Posiada')],
                default='n/a',
                max_length=5,
                verbose_name='Inne imię czapkowe'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='imie_piwne_2',
            field=models.CharField(
                blank=True,
                default='Nie dotyczy',
                max_length=100,
                verbose_name='Wpisz inne imię czapkowe:'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='czapka_1',
            field=models.ForeignKey(
                default=czapki.models.Czapka.get_dont_know_czapka,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_%(class)s_posiadacze_pierwszy_wybor',
                to='czapki.czapka',
                verbose_name='Czapka'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='czapka_2',
            field=models.ForeignKey(
                default=czapki.models.Czapka.get_not_applicable_czapka,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_%(class)s_posiadacze_drugi_wybor',
                to='czapki.czapka',
                verbose_name='Inna czapka'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='rodzic_1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_dzieci_pierwszy_wybor',
                to='osoby.oldczlonek',
                verbose_name='Rodzic czapkowy'
            ),
        ),
        migrations.AlterField(
            model_name='oldczlonek',
            name='rodzic_2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='old_dzieci_drugi_wybor',
                to='osoby.oldczlonek',
                verbose_name='Drugi rodzic czapkowy'
            ),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='bibendi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_bibendi_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Bibendi'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='cantandi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_cantandi_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Cantandi'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='kasztelan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kasztelan_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Kasztelan'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='kontakt_z_SKNHI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kontakt_z_SKNHI_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Kontakt Z SKNHI'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='kontakt_z_SSUJ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kontakt_z_SSUJ_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Kontakt Z SSUJ'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='magister_disciplinae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_magister_disciplinae_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Magister Disciplinae'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='skarbnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_skarbnik_dawnego_zarzadu', to='osoby.oldczlonek', verbose_name='Skarbnik'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='czlonek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.oldczlonek', verbose_name='Członek'),
        ),
        migrations.AlterField(
            model_name='imieszlacheckie',
            name='imie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osoby.oldczlonek', verbose_name='Imię szlacheckie'),
        ),
        migrations.AlterField(
            model_name='wielkimistrz',
            name='imie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.oldczlonek', verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='cantandi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_cantandi', to='osoby.oldczlonek', verbose_name='Cantandi'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='kasztelan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kasztelan', to='osoby.oldczlonek', verbose_name='Kasztelan'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='sekretarz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_sekretarz', to='osoby.oldczlonek', verbose_name='Sekretarz'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='skarbnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_skarbnik', to='osoby.oldczlonek', verbose_name='Skarbnik'),
        ),
        migrations.AlterField(
            model_name='zwierzeczapkowe',
            name='czlonek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.oldczlonek', verbose_name='Członek'),
        ),
    ]
