# Generated by Django 5.2.1 on 2025-07-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0007_alter_innaoldosoba_options_alter_oldbean_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldbean',
            name='czapka_1',
        ),
        migrations.RemoveField(
            model_name='oldbean',
            name='czapka_2',
        ),
        migrations.RemoveField(
            model_name='oldbean',
            name='rodzic_1',
        ),
        migrations.RemoveField(
            model_name='oldbean',
            name='rodzic_2',
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='bean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.bean', verbose_name='Bean'),
        ),
        migrations.RemoveField(
            model_name='oldczlonek',
            name='czapka_1',
        ),
        migrations.RemoveField(
            model_name='oldczlonek',
            name='czapka_2',
        ),
        migrations.RemoveField(
            model_name='oldczlonek',
            name='rodzic_1',
        ),
        migrations.RemoveField(
            model_name='oldczlonek',
            name='rodzic_2',
        ),
        migrations.AlterField(
            model_name='zwierzeczapkowe',
            name='czlonek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.czlonek', verbose_name='Członek'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='kontakt_z_SKNHI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kontakt_z_SKNHI_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Kontakt Z SKNHI'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='kontakt_z_SSUJ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kontakt_z_SSUJ_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Kontakt Z SSUJ'),
        ),
        migrations.AlterField(
            model_name='imieszlacheckie',
            name='imie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osoby.czlonek', verbose_name='Imię szlacheckie'),
        ),
        migrations.AlterField(
            model_name='wielkimistrz',
            name='imie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.czlonek', verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='sekretarz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_sekretarz', to='osoby.czlonek', verbose_name='Sekretarz'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='skarbnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_skarbnik_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Skarbnik'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='skarbnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_skarbnik', to='osoby.czlonek', verbose_name='Skarbnik'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='bibendi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_bibendi_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Bibendi'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='magister_disciplinae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_magister_disciplinae_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Magister Disciplinae'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='czlonek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osoby.czlonek', verbose_name='Członek'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='kasztelan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kasztelan_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Kasztelan'),
        ),
        migrations.AlterField(
            model_name='dawnyzarzad',
            name='cantandi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_cantandi_dawnego_zarzadu', to='osoby.czlonek', verbose_name='Cantandi'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='kasztelan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_kasztelan', to='osoby.czlonek', verbose_name='Kasztelan'),
        ),
        migrations.AlterField(
            model_name='zarzad',
            name='cantandi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kadencje_jako_cantandi', to='osoby.czlonek', verbose_name='Cantandi'),
        ),
        migrations.DeleteModel(
            name='InnaOldOsoba',
        ),
        migrations.DeleteModel(
            name='OldBean',
        ),
    ]
