# Generated by Django 5.2.1 on 2025-07-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0008_remove_oldbean_czapka_1_remove_oldbean_czapka_2_and_more'),
        ('kronika', '0005_alter_charakterystykadzialanzarzadu_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldCzlonek',
        ),
    ]
