# Generated by Django 5.2.1 on 2025-07-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0009_delete_oldczlonek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innaosoba',
            old_name='bractwo',
            new_name='bractwo_do_ktorego_nalezy',
        ),
    ]
