# Generated by Django 5.2.1 on 2025-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0010_rename_bractwo_innaosoba_bractwo_do_ktorego_nalezy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="pewnosc_stazu",
            field=models.CharField(
                choices=[
                    ("T", "Na pewno wcześniej się nie pojawiał"),
                    ("N", "Ale mógł pojawić się wcześniej"),
                ],
                default="T",
                verbose_name="Pewność roku pojawienia się",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="imie_piwne_1",
            field=models.CharField(
                blank=True,
                default="Nie wiem",
                max_length=100,
                verbose_name="Imię czapkowe",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="imie_piwne_1_wybor",
            field=models.CharField(
                choices=[
                    ("n/a", "Nie dotyczy"),
                    ("d/n", "Nie wiem"),
                    ("other", "Posiada"),
                ],
                default=("d/n", "Nie wiem"),
                max_length=5,
                verbose_name="Czy posiada imię czapkowe",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="imie_piwne_2",
            field=models.CharField(
                blank=True,
                default="Nie dotyczy",
                max_length=100,
                verbose_name="Inne imię czapkowe",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="imie_piwne_2_wybor",
            field=models.CharField(
                choices=[
                    ("n/a", "Nie dotyczy"),
                    ("d/n", "Nie wiem"),
                    ("other", "Posiada"),
                ],
                default=("n/a", "Nie dotyczy"),
                max_length=5,
                verbose_name="Czy posiada inne imię czapkowe",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="ochrzczony",
            field=models.CharField(
                choices=[("T", "Tak"), ("N", "Nie"), ("d/n", "Nie wiem")],
                default=("d/n", "Nie wiem"),
                max_length=5,
                verbose_name="Czy ochrzczony",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="pewnosc_stazu",
            field=models.CharField(
                choices=[
                    ("T", "Na pewno wcześniej się nie pojawiał"),
                    ("N", "Ale mógł pojawić się wcześniej"),
                ],
                default="T",
                verbose_name="Pewność roku pojawienia się",
            ),
        ),
    ]
