# Generated by Django 5.2.1 on 2025-07-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0018_alter_wydarzeniehistoryczne_data_and_more"),
        (
            "osoby",
            "0011_alter_bean_pewnosc_stazu_alter_czlonek_imie_piwne_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dawnyzarzad",
            name="kadencja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kronika.kadencja",
                verbose_name="Kadencja",
            ),
        ),
        migrations.AlterField(
            model_name="zarzad",
            name="kadencja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kronika.kadencja",
                verbose_name="Kadencja",
            ),
        ),
    ]
