# Generated by Django 5.2.1 on 2025-07-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0002_alter_obrazwydarzenie_widoczne_osoby_and_more"),
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
    ]

    operations = [
        migrations.AddField(
            model_name="czlonek",
            name="depositio_beanorum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendarz.wydarzenie",
                verbose_name="Depositio beanorum",
            ),
        ),
    ]
