# Generated by Django 5.2.1 on 2025-07-27 11:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0020_alter_charakterystykadzialanzarzadu_options_and_more"),
        ("osoby", "0013_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Zarzad",
            new_name="NowyZarzad",
        ),
    ]
