# Generated by Django 5.2.1 on 2025-07-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "kronika",
            "0020_alter_charakterystykadzialanzarzadu_options_and_more",
        ),
        ("osoby", "0014_rename_zarzad_to_nowyzarzad "),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="cantandi",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="kadencja",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="kasztelan",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="sekretarz",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="skarbnik",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="wielki_mistrz",
        ),
        migrations.CreateModel(
            name="Zarzad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantandi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_cantandi_dawnego_zarzadu",
                        to="osoby.czlonek",
                        verbose_name="Cantandi",
                    ),
                ),
                (
                    "kadencja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kronika.kadencja",
                        verbose_name="Kadencja",
                    ),
                ),
                (
                    "kasztelan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_kasztelan",
                        to="osoby.czlonek",
                        verbose_name="Kasztelan",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "skarbnik",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_skarbnik",
                        to="osoby.czlonek",
                        verbose_name="Skarbnik",
                    ),
                ),
                (
                    "wielki_mistrz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_wielki_mistrz",
                        to="osoby.wielkimistrz",
                        verbose_name="Wielki Mistrz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zarząd",
                "verbose_name_plural": "Zarządy",
                "ordering": ["kadencja"],
            },
        ),
    ]
