# Generated by Django 5.2.1 on 2025-07-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0015_remove_nowyzarzad_cantandi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="bibendi",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="cantandi",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="kadencja",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="kasztelan",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="kontakt_z_SKNHI",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="kontakt_z_SSUJ",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="magister_disciplinae",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="skarbnik",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="wielki_mistrz",
        ),
    ]
