# Generated by Django 5.2.1 on 2025-07-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0016_remove_dawnyzarzad_bibendi_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DawnyZarzad",
        ),
        migrations.DeleteModel(
            name="NowyZarzad",
        ),
    ]
