# Generated by Django 5.2.1 on 2025-07-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0017_delete_dawnyzarzad_delete_nowyzarzad"),
    ]

    operations = [
        migrations.CreateModel(
            name="DawnyZarzad",
            fields=[
                (
                    "zarzad_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osoby.zarzad",
                    ),
                ),
                (
                    "bibendi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_bibendi_dawnego_zarzadu",
                        to="osoby.czlonek",
                        verbose_name="Bibendi",
                    ),
                ),
                (
                    "kontakt_z_SKNHI",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_kontakt_z_SKNHI_dawnego_zarzadu",
                        to="osoby.czlonek",
                        verbose_name="Kontakt Z SKNHI",
                    ),
                ),
                (
                    "kontakt_z_SSUJ",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_kontakt_z_SSUJ_dawnego_zarzadu",
                        to="osoby.czlonek",
                        verbose_name="Kontakt Z SSUJ",
                    ),
                ),
                (
                    "magister_disciplinae",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_magister_disciplinae_dawnego_zarzadu",
                        to="osoby.czlonek",
                        verbose_name="Magister Disciplinae",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dawny Zarząd",
                "verbose_name_plural": "Dawne Zarządy",
                "ordering": ["-kadencja"],
            },
            bases=("osoby.zarzad",),
        ),
        migrations.CreateModel(
            name="NowyZarzad",
            fields=[
                (
                    "zarzad_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osoby.zarzad",
                    ),
                ),
                (
                    "sekretarz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kadencje_jako_sekretarz",
                        to="osoby.czlonek",
                        verbose_name="Sekretarz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zarząd",
                "verbose_name_plural": "Zarządy",
                "ordering": ["-kadencja"],
            },
            bases=("osoby.zarzad",),
        ),
    ]
