# Generated by Django 5.2.1 on 2025-07-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kronika",
            "0020_alter_charakterystykadzialanzarzadu_options_and_more",
        ),
        ("osoby", "0018_dawnyzarzad_nowyzarzad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dawnyzarzad",
            options={
                "ordering": ["-kadencja"],
                "verbose_name": "Zarząd",
                "verbose_name_plural": "Zarządy w starej formule",
            },
        ),
        migrations.AlterModelOptions(
            name="nowyzarzad",
            options={
                "ordering": ["-kadencja"],
                "verbose_name": "Zarząd",
                "verbose_name_plural": "Zarządy w obecnej formule",
            },
        ),
        migrations.AlterField(
            model_name="dawnyzarzad",
            name="bibendi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_bibendi_dawnego_zarzadu",
                to="osoby.czlonek",
                verbose_name="Bibendi",
            ),
        ),
        migrations.AlterField(
            model_name="dawnyzarzad",
            name="kontakt_z_SKNHI",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_kontakt_z_SKNHI_dawnego_zarzadu",
                to="osoby.czlonek",
                verbose_name="Kontakt Z SKNHI",
            ),
        ),
        migrations.AlterField(
            model_name="dawnyzarzad",
            name="kontakt_z_SSUJ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_kontakt_z_SSUJ_dawnego_zarzadu",
                to="osoby.czlonek",
                verbose_name="Kontakt Z SSUJ",
            ),
        ),
        migrations.AlterField(
            model_name="dawnyzarzad",
            name="magister_disciplinae",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_magister_disciplinae_dawnego_zarzadu",
                to="osoby.czlonek",
                verbose_name="Magister Disciplinae",
            ),
        ),
        migrations.AlterField(
            model_name="nowyzarzad",
            name="sekretarz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_sekretarz",
                to="osoby.czlonek",
                verbose_name="Sekretarz",
            ),
        ),
        migrations.AlterField(
            model_name="zarzad",
            name="cantandi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_cantandi_dawnego_zarzadu",
                to="osoby.czlonek",
                verbose_name="Cantandi",
            ),
        ),
        migrations.AlterField(
            model_name="zarzad",
            name="kadencja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kronika.kadencja",
                verbose_name="Kadencja",
            ),
        ),
        migrations.AlterField(
            model_name="zarzad",
            name="kasztelan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_kasztelan",
                to="osoby.czlonek",
                verbose_name="Kasztelan",
            ),
        ),
        migrations.AlterField(
            model_name="zarzad",
            name="skarbnik",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kadencje_jako_skarbnik",
                to="osoby.czlonek",
                verbose_name="Skarbnik",
            ),
        ),
    ]
