# Generated by Django 5.2.1 on 2025-07-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0019_alter_dawnyzarzad_options_alter_nowyzarzad_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="halloffame",
            name="osoba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wzmianka_w_hall_of_fame",
                to="osoby.osoba",
                verbose_name="Osoba",
            ),
        ),
    ]
