# Generated by Django 5.2.1 on 2025-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0020_halloffame_osoba"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="halloffame",
            name="bean",
        ),
        migrations.RemoveField(
            model_name="halloffame",
            name="czlonek",
        ),
    ]
