# Generated by Django 5.2.1 on 2025-07-28 16:37

import django.db.models.deletion
from django.db import migrations, models


def link_existing_osoba_and_zarzad_to_existing_byt(apps, schema_editor):
    Byt = apps.get_model("osoby", "Byt")
    Osoba = apps.get_model("osoby", "Osoba")
    Zarzad = apps.get_model("osoby", "Zarzad")
    db_alias = schema_editor.connection.alias

    for osoba in Osoba.objects.using(db_alias).all():
        osoba.byt_ptr = Byt.objects.using(db_alias).get(id=osoba.id)
        osoba.save()

    for zarzad in Zarzad.objects.using(db_alias).all():
        zarzad.byt_ptr = Byt.objects.using(db_alias).get(id=zarzad.id + 194)
        zarzad.save()


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0022_byt"),
    ]

    operations = [
        migrations.AddField(
            model_name="osoba",
            name="byt_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                # primary_key=True,
                null=True,
                serialize=False,
                to="osoby.byt",
            ),
        ),
        migrations.AddField(
            model_name="zarzad",
            name="byt_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                # primary_key=True,
                null=True,
                serialize=False,
                to="osoby.byt",
            ),
        ),
        migrations.RunPython(link_existing_osoba_and_zarzad_to_existing_byt),
        migrations.RemoveField(
            model_name="osoba",
            name="id",
        ),
        migrations.RemoveField(
            model_name="osoba",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="zarzad",
            name="id",
        ),
        migrations.RemoveField(
            model_name="zarzad",
            name="polymorphic_ctype",
        ),
        migrations.AlterField(
            model_name="osoba",
            name="byt_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="osoby.byt",
            ),
        ),
        migrations.AlterField(
            model_name="zarzad",
            name="byt_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="osoby.byt",
            ),
        ),
    ]
