# Generated by Django 5.2.1 on 2025-07-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0026_alter_zadaniechrzcielne_autor"),
        ("osoby", "0024_set_polymorphic_ctype"),
    ]

    operations = [
        migrations.CreateModel(
            name="KomisjaRewizyjna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dzialalnosc",
                    models.TextField(blank=True, null=True, verbose_name="Działalność"),
                ),
                (
                    "kadencja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kronika.kadencja",
                        verbose_name="Kadencja",
                    ),
                ),
                (
                    "sklad",
                    models.ManyToManyField(
                        blank=True, null=True, to="osoby.osoba", verbose_name="Skład"
                    ),
                ),
            ],
            options={
                "verbose_name": "Komisja rewizyjna",
                "verbose_name_plural": "Komisja rewizyjna",
                "ordering": ["kadencja"],
            },
        ),
    ]
