# Generated by Django 5.2.1 on 2025-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0025_komisjarewizyjna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="komisjarewizyjna",
            name="sklad",
            field=models.ManyToManyField(
                blank=True, to="osoby.osoba", verbose_name="Skład"
            ),
        ),
    ]
