# Generated by Django 5.2.1 on 2025-08-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0005_alter_wydarzeniekalendarzowe_data_rozpoczecia_and_more"),
        ("osoby", "0026_alter_komisjarewizyjna_sklad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czlonek",
            name="depositio_beanorum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Depositio beanorum",
            ),
        ),
    ]
