# Generated by Django 5.2.1 on 2025-08-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0030_remove_wydarzeniehistoryczne_data"),
        ("osoby", "0027_alter_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.AddField(
            model_name="zarzad",
            name="koniec_urzedu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kronika.wydarzeniehistoryczne",
                verbose_name="Wydarzenie kończące urząd w tym składzie",
            ),
        ),
        migrations.AddField(
            model_name="zarzad",
            name="wybory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zarzad_wybrany_na_wydarzeniu",
                to="kronika.wydarzeniehistoryczne",
                verbose_name="Wybory",
            ),
        ),
    ]
