# Generated by Django 5.2.1 on 2025-08-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0028_zarzad_koniec_urzedu_zarzad_wybory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zarzad",
            options={
                "ordering": ["-wybory__wydarzenie__data_rozpoczecia"],
                "verbose_name": "Zarząd",
                "verbose_name_plural": "Zarządy",
            },
        ),
    ]
