# Generated by Django 5.2.1 on 2025-08-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0029_alter_zarzad_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="byt",
            options={
                "ordering": ["id"],
                "verbose_name": "Byt",
                "verbose_name_plural": "Byty",
            },
        ),
    ]
