# Generated by Django 5.2.1 on 2025-08-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0030_alter_byt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="byt",
            options={"base_manager_name": "objects"},
        ),
    ]
