# Generated by Django 5.2.1 on 2025-08-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0031_alter_byt_options"),
        ("zrodla", "0012_alter_zrodlo_autorzy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zespol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("cel", models.TextField(blank=True, verbose_name="Cele")),
                (
                    "czlonkowie",
                    models.ManyToManyField(
                        blank=True, to="osoby.osoba", verbose_name="Członkowie"
                    ),
                ),
                (
                    "dokument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zrodla.dokument",
                        verbose_name="Dokument powołujący",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zespół",
                "verbose_name_plural": "Zespoły",
                "ordering": ["-dokument__data", "nazwa"],
            },
        ),
        migrations.CreateModel(
            name="KoordynatorZespolu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rozpoczecie_urzedu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Rozpoczęcie urzędu"
                    ),
                ),
                (
                    "koniec_urzedu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Koniec urzędu"
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.osoba",
                        verbose_name="Osoba",
                    ),
                ),
                (
                    "zespol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.zespol",
                        verbose_name="Zespół",
                    ),
                ),
            ],
            options={
                "verbose_name": "Koordynator Zespołu",
                "verbose_name_plural": "Koordynatorzy zespołów",
                "ordering": ["zespol", "-rozpoczecie_urzedu"],
            },
        ),
    ]
