# Generated by Django 5.2.1 on 2025-08-27 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0010_depositiobeanorum_dokument"),
        ("osoby", "0032_zespol_koordynatorzespolu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czlonek",
            name="depositio_beanorum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendarz.depositiobeanorum",
                verbose_name="Depositio beanorum",
            ),
        ),
    ]
