# Generated by Django 5.2.1 on 2025-08-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0033_alter_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egzekutor",
            fields=[
                (
                    "koordynatorzespolu_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osoby.koordynatorzespolu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Egzekutor",
                "verbose_name_plural": "Egzekutorzy",
                "ordering": ["zespol", "-rozpoczecie_urzedu"],
            },
            bases=("osoby.koordynatorzespolu",),
        ),
    ]
