# Generated by Django 5.2.1 on 2025-08-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0035_organizacja_organizacjastudencka_bractwo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizacjastudencka",
            options={
                "ordering": ["nazwa"],
                "verbose_name": "Organizacja studencka",
                "verbose_name_plural": "Organizacje studenckie",
            },
        ),
        migrations.AlterField(
            model_name="innaosoba",
            name="bractwo_do_ktorego_nalezy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="czlonkowie_bractwa",
                to="osoby.bractwo",
                verbose_name="Bractwo",
            ),
        ),
    ]
