# Generated by Django 5.2.1 on 2025-08-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0036_alter_organizacjastudencka_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="komisjarewizyjna",
            name="przewodniczacy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="przewodzi_komisjom",
                to="osoby.osoba",
                verbose_name="Przewodniczący",
            ),
        ),
    ]
