# Generated by Django 5.2.1 on 2025-08-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0036_alter_zadaniechrzcielne_options"),
        ("osoby", "0037_komisjarewizyjna_przewodniczacy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KomisjaRewizyjna",
            new_name="KomisjaRewizyjna1",
        ),
        migrations.AlterModelOptions(
            name="komisjarewizyjna1",
            options={
                "ordering": ["-kadencja"],
                "verbose_name": "Komisja rewizyjna",
                "verbose_name_plural": "Komisja rewizyjna",
            },
        ),
    ]
