# Generated by Django 5.2.1 on 2025-08-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0036_alter_zadaniechrzcielne_options"),
        ("osoby", "0038_rename_komisjarewizyjna_komisjarewizyjna1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KomisjaRewizyjna",
            fields=[
                (
                    "byt_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osoby.byt",
                    ),
                ),
                (
                    "dzialalnosc",
                    models.TextField(blank=True, null=True, verbose_name="Działalność"),
                ),
                (
                    "kadencja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kronika.kadencja",
                        verbose_name="Kadencja",
                    ),
                ),
                (
                    "przewodniczacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="przewodzi_komisjom",
                        to="osoby.osoba",
                        verbose_name="Przewodniczący",
                    ),
                ),
                (
                    "sklad",
                    models.ManyToManyField(
                        blank=True, to="osoby.osoba", verbose_name="Skład"
                    ),
                ),
            ],
            options={
                "verbose_name": "Komisja rewizyjna",
                "verbose_name_plural": "Komisja rewizyjna",
                "ordering": ["-kadencja"],
            },
            bases=("osoby.byt",),
        ),
        migrations.DeleteModel(
            name="KomisjaRewizyjna1",
        ),
    ]
