# Generated by Django 5.2.1 on 2025-08-31 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0019_rename_depositiobeanorum_chrzest_and_more"),
        ("osoby", "0039_komisjarewizyjna_delete_komisjarewizyjna1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czlonek",
            name="depositio_beanorum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendarz.chrzest",
                verbose_name="Chrzest",
            ),
        ),
    ]
