# Generated by Django 5.2.1 on 2025-08-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0040_alter_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="czlonek",
            old_name="depositio_beanorum",
            new_name="chrzest",
        ),
    ]
