# Generated by Django 5.2.1 on 2025-09-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0042_bean_search_text_czlonek_search_text_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Egzekutor",
        ),
    ]
