# Generated by Django 5.2.1 on 2025-09-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0043_delete_egzekutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Egzekutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_text", models.TextField(blank=True, editable=False)),
                (
                    "rozpoczecie_urzedu",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Rozpoczęcie urzędu",
                    ),
                ),
                (
                    "koniec_urzedu",
                    models.DateField(
                        blank=True, null=True, verbose_name="Koniec urzędu"
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.osoba",
                        verbose_name="Osoba",
                    ),
                ),
                (
                    "zespol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.zespol",
                        verbose_name="Zespół",
                    ),
                ),
            ],
            options={
                "verbose_name": "Egzekutor",
                "verbose_name_plural": "Egzekutorzy",
                "ordering": ["zespol", "-rozpoczecie_urzedu"],
            },
        ),
    ]
