# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0044_egzekutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="bean",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="czlonek",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="dawnyzarzad",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="egzekutor",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="halloffame",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="imieszlacheckie",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="innaosoba",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="komisjarewizyjna",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="koordynatorzespolu",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="nowyzarzad",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="organizacja",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="wielkimistrz",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="zespol",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="zwierzeczapkowe",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
