# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0049_bean_search_dict_czlonek_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bean",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="czlonek",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="egzekutor",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="halloffame",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="imieszlacheckie",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="innaosoba",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="komisjarewizyjna",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="koordynatorzespolu",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="organizacja",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="wielkimistrz",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="zespol",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="zwierzeczapkowe",
            name="search_text",
        ),
    ]
