# Generated by Django 5.2.1 on 2025-09-11 10:43

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0050_remove_bean_search_text_remove_czlonek_search_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="byt",
            options={},
        ),
        migrations.RemoveField(
            model_name="bean",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="bean",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="czlonek",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="czlonek",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="dawnyzarzad",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="innaosoba",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="innaosoba",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="komisjarewizyjna",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="komisjarewizyjna",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="nowyzarzad",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="organizacja",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="organizacja",
            name="tsv",
        ),
        migrations.AddField(
            model_name="byt",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="byt",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
