# Generated by Django 5.2.1 on 2025-10-11 11:28

import czapki.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0016_alter_czapka_search_dict_and_more"),
        ("osoby", "0054_bean_pierwsze_wydarzenie_czlonek_pierwsze_wydarzenie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="czapka_1",
            field=models.ForeignKey(
                default=czapki.models.Czapka.get_not_applicable_czapka,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_posiadacze_pierwszy_wybor",
                to="czapki.czapka",
                verbose_name="Czapka",
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="staz",
            field=models.IntegerField(
                choices=[
                    (2009, "2009"),
                    (2010, "2010"),
                    (2011, "2011"),
                    (2012, "2012"),
                    (2013, "2013"),
                    (2014, "2014"),
                    (2015, "2015"),
                    (2016, "2016"),
                    (2017, "2017"),
                    (2018, "2018"),
                    (2019, "2019"),
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (1111111111, "Nie wiem"),
                ],
                default=2025,
                verbose_name="Rok pojawienia się",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="czapka_1",
            field=models.ForeignKey(
                default=czapki.models.Czapka.get_not_applicable_czapka,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_posiadacze_pierwszy_wybor",
                to="czapki.czapka",
                verbose_name="Czapka",
            ),
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="staz",
            field=models.IntegerField(
                choices=[
                    (2009, "2009"),
                    (2010, "2010"),
                    (2011, "2011"),
                    (2012, "2012"),
                    (2013, "2013"),
                    (2014, "2014"),
                    (2015, "2015"),
                    (2016, "2016"),
                    (2017, "2017"),
                    (2018, "2018"),
                    (2019, "2019"),
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (1111111111, "Nie wiem"),
                ],
                default=2025,
                verbose_name="Rok pojawienia się",
            ),
        ),
    ]
