# Generated by Django 5.2.1 on 2025-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0055_alter_bean_czapka_1_alter_bean_staz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czlonek",
            name="status",
            field=models.CharField(
                choices=[
                    ("CZ", "Członek zwyczajny"),
                    ("CW", "Członek wspierający"),
                    ("X", 'Wydalony (np. "Jezus")'),
                    ("W", "Weteran"),
                    ("H", "Członek Honoris Causa"),
                    ("d/n", "Nie wiem"),
                ],
                default="d/n",
                max_length=5,
                verbose_name="Status",
            ),
        ),
    ]
