# Generated by Django 5.2.1 on 2025-11-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0056_alter_czlonek_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bean",
            old_name="pewnosc_stazu",
            new_name="pewnosc_stazu_1",
        ),
        migrations.RenameField(
            model_name="czlonek",
            old_name="pewnosc_stazu",
            new_name="pewnosc_stazu_1",
        ),
        migrations.AlterField(
            model_name="czlonek",
            name="aktywnosc",
            field=models.CharField(
                choices=[
                    ("A", "Częsta"),
                    ("M", "Tylko w mediach/rzadka"),
                    ("N", "Brak"),
                    ("O", "Negatywna"),
                ],
                default="N",
                max_length=1,
                verbose_name="Aktywność",
            ),
        ),
    ]
