# Generated by Django 5.2.1 on 2025-11-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0057_rename_pewnosc_stazu_bean_pewnosc_stazu_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bean",
            name="pewnosc_stazu",
            field=models.BooleanField(
                default=True, verbose_name="Pewność roku pojawienia się"
            ),
        ),
        migrations.AddField(
            model_name="czlonek",
            name="pewnosc_stazu",
            field=models.BooleanField(
                default=True, verbose_name="Pewność roku pojawienia się"
            ),
        ),
    ]
