# Generated by Django 5.2.1 on 2025-11-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0058_bean_pewnosc_stazu_czlonek_pewnosc_stazu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bean",
            name="pewnosc_stazu_1",
        ),
        migrations.RemoveField(
            model_name="czlonek",
            name="pewnosc_stazu_1",
        ),
    ]
