# Generated by Django 5.2.1 on 2025-11-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0059_remove_bean_pewnosc_stazu_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bean",
            name="aktywnosc",
            field=models.CharField(
                choices=[
                    ("A", "Częsta"),
                    ("M", "Tylko w mediach/rzadka"),
                    ("N", "Brak"),
                    ("O", "Negatywna"),
                ],
                default="A",
                max_length=1,
                verbose_name="Aktywność",
            ),
        ),
    ]
