# Generated by Django 5.2.1 on 2025-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0060_bean_aktywnosc"),
    ]

    operations = [
        migrations.AddField(
            model_name="osoba",
            name="archiwum",
            field=models.BooleanField(default=False),
        ),
    ]
