# Generated by Django 5.2.1 on 2025-08-28 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("osoby", "0034_egzekutor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Konto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kraj",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Kraj"
                    ),
                ),
                (
                    "numer_konta",
                    models.CharField(
                        blank=True, max_length=34, verbose_name="Numer konta"
                    ),
                ),
                (
                    "adres",
                    models.TextField(
                        blank=True, verbose_name="Adres właściciela"
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "wlasciciel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.byt",
                        verbose_name="Właściciel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konto",
                "verbose_name_plural": "Konta",
                "ordering": ["wlasciciel"],
            },
        ),
        migrations.CreateModel(
            name="Transakcja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("przychod", "Przychód"),
                            ("wydatek", "Wydatek"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "kwota",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now=True, verbose_name="Data zaksięgowania"
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "dodal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dodał/dodała",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transakcje",
                        to="skarbiec.konto",
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transakcja",
                "verbose_name_plural": "Transakcje",
                "ordering": ["-data"],
            },
        ),
    ]
