# Generated by Django 5.2.1 on 2025-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="konto",
            name="kraj",
        ),
    ]
