# Generated by Django 5.2.1 on 2025-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0003_transakcja_kwota_currency_alter_transakcja_kwota"),
    ]

    operations = [
        migrations.AddField(
            model_name="transakcja",
            name="tytul",
            field=models.TextField(default="", verbose_name="Tytuł"),
            preserve_default=False,
        ),
    ]
