# Generated by Django 5.2.1 on 2025-08-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0004_transakcja_tytul"),
        ("zrodla", "0015_remove_rozliczenie_transakcja"),
    ]

    operations = [
        migrations.AddField(
            model_name="transakcja",
            name="rozliczenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rozliczane_transakcje",
                to="zrodla.rozliczenie",
                verbose_name="Rozliczenie",
            ),
        ),
        migrations.AlterField(
            model_name="transakcja",
            name="konto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transakcje_z_tego_konta",
                to="skarbiec.konto",
                verbose_name="Konto",
            ),
        ),
    ]
