# Generated by Django 5.2.1 on 2025-08-28 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0005_transakcja_rozliczenie_alter_transakcja_konto"),
    ]

    operations = [
        migrations.AddField(
            model_name="konto",
            name="nazwa_alternatywna",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nazwa alternatywna"
            ),
        ),
        migrations.AlterField(
            model_name="transakcja",
            name="data",
            field=models.DateField(
                default=datetime.date(2025, 8, 28), verbose_name="Data zaksięgowania"
            ),
        ),
    ]
