# Generated by Django 5.2.1 on 2025-08-28 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0006_konto_nazwa_alternatywna_alter_transakcja_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transakcja",
            name="data",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data zaksięgowania"
            ),
        ),
    ]
