# Generated by Django 5.2.1 on 2025-08-28 21:26

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0007_alter_transakcja_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="konto",
            options={
                "ordering": ["wlasciciel", "nazwa_alternatywna"],
                "verbose_name": "Konto",
                "verbose_name_plural": "Konta",
            },
        ),
        migrations.AlterField(
            model_name="transakcja",
            name="kwota",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="PLN",
                max_digits=14,
                verbose_name="Kwota (z kropką zamiast przecinka)",
            ),
        ),
    ]
