# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0008_alter_konto_options_alter_transakcja_kwota"),
    ]

    operations = [
        migrations.AddField(
            model_name="konto",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="transakcja",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
