# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0009_konto_search_text_transakcja_search_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="konto",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="transakcja",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
