# Generated by Django 5.2.1 on 2025-09-08 13:36

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0010_konto_fields_positions_transakcja_fields_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="konto",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="transakcja",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
