# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0012_konto_search_dict_transakcja_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="konto",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="konto",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="transakcja",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="transakcja",
            name="search_dict",
        ),
    ]
