# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0014_konto_search_dict_transakcja_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="konto",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="transakcja",
            name="search_text",
        ),
    ]
