# Generated by Django 5.2.1 on 2025-09-12 13:55

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0015_remove_konto_search_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="konto",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="transakcja",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
