# Generated by Django 5.2.1 on 2025-09-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tytul",
                    models.CharField(max_length=40, verbose_name="Nazwa aplikacji"),
                ),
                (
                    "opis",
                    models.TextField(blank=True, null=True, verbose_name="Krótki opis"),
                ),
                (
                    "ikona",
                    models.CharField(
                        blank=True,
                        help_text="Lokalizacja ikony w static/images/apps/ np. blog.png",
                        max_length=40,
                        null=True,
                        verbose_name="Ikona",
                    ),
                ),
                (
                    "adres_url",
                    models.CharField(
                        blank=True,
                        help_text="Adres URL głównego widoku aplikacji, np. 'blog:index'",
                        max_length=40,
                        null=True,
                        verbose_name="Django URL",
                    ),
                ),
            ],
            options={
                "ordering": ["tytul"],
            },
        ),
    ]
