# Generated by Django 5.2.1 on 2025-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="opis",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Krótki opis"
            ),
        ),
    ]
