# Generated by Django 5.2.1 on 2025-10-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_app_opis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="App",
        ),
    ]
