# Generated by Django 5.2.1 on 2025-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="adres_url",
            field=models.CharField(
                blank=True,
                choices=[],
                help_text="Adres URL głównego widoku aplikacji, np. 'blog:index'",
                max_length=40,
                null=True,
                verbose_name="Django URL",
            ),
        ),
    ]
