# Generated by Django 5.2.1 on 2025-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_app_adres_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="tytul",
            field=models.CharField(
                choices=[
                    ("core", "core"),
                    ("czapki", "czapki"),
                    ("dashboard", "dashboard"),
                    ("drzewo", "drzewo"),
                    ("encyklopedia", "encyklopedia"),
                    ("honory", "honory"),
                    ("kalendarz", "kalendarz"),
                    ("kronika", "kronika"),
                    ("miejsca", "miejsca"),
                    ("multimedia", "multimedia"),
                    ("osoby", "osoby"),
                    ("prawo", "prawo"),
                    ("skarbiec", "skarbiec"),
                    ("slowniczek_lacinski", "slowniczek_lacinski"),
                    ("spiewnik", "spiewnik"),
                    ("wyszukiwarka", "wyszukiwarka"),
                    ("zrodla", "zrodla"),
                ],
                max_length=40,
                verbose_name="Nazwa aplikacji",
            ),
        ),
    ]
