# Generated by Django 5.2.1 on 2025-10-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_app_tytul"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={"ordering": ["nazwa", "aplikacja"]},
        ),
        migrations.RemoveField(
            model_name="app",
            name="tytul",
        ),
        migrations.AddField(
            model_name="app",
            name="aplikacja",
            field=models.CharField(
                choices=[
                    ("core", "core"),
                    ("czapki", "czapki"),
                    ("dashboard", "dashboard"),
                    ("drzewo", "drzewo"),
                    ("encyklopedia", "encyklopedia"),
                    ("honory", "honory"),
                    ("kalendarz", "kalendarz"),
                    ("kronika", "kronika"),
                    ("miejsca", "miejsca"),
                    ("multimedia", "multimedia"),
                    ("osoby", "osoby"),
                    ("prawo", "prawo"),
                    ("skarbiec", "skarbiec"),
                    ("slowniczek_lacinski", "slowniczek_lacinski"),
                    ("spiewnik", "spiewnik"),
                    ("wyszukiwarka", "wyszukiwarka"),
                    ("zrodla", "zrodla"),
                ],
                default="",
                max_length=40,
                verbose_name="Aplikacja Django",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="nazwa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nazwa Aplikacji"
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="adres_url",
            field=models.CharField(
                blank=True,
                help_text="Adres URL głównego widoku aplikacji, np. 'blog:index'",
                max_length=40,
                null=True,
                verbose_name="Django URL",
            ),
        ),
    ]
