# Generated by Django 5.2.1 on 2025-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_app_options_remove_app_tytul_app_aplikacja_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="ikona",
            field=models.CharField(
                blank=True,
                help_text="Lokalizacja ikony w static/images/apps/ np. blog.svg",
                max_length=40,
                null=True,
                verbose_name="Ikona",
            ),
        ),
    ]
