# Generated by Django 5.2 on 2025-05-01 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
                ('typ', models.CharField(choices=[('Pub', 'Pub'), ('Szczyt', 'Szczyt'), ('ObKult', 'Obiekt kultury')], max_length=10, verbose_name='Typ miejsca')),
            ],
            options={
                'verbose_name': 'Miejsce',
                'verbose_name_plural': 'Miejsca',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Proces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data_rozpoczecia', models.DateField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia')),
                ('data_zakonczenia', models.DateField(default=django.utils.timezone.now, verbose_name='Data zakończenia')),
            ],
            options={
                'verbose_name': 'Proces',
                'verbose_name_plural': 'Procesy',
                'ordering': ['-data_rozpoczecia'],
            },
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('opis', models.TextField(verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SpotkanieCzapkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('typ', models.CharField(choices=[('I', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('Groby', 'Groby'), ('Ognisko', 'Ognisko'), ('OD', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyc', 'Wycieczka'), ('Wybory', 'Wybory'), ('UZ', 'Ułańskie Zdrowie')], max_length=10, verbose_name='Typ spotkania')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('miejsce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.miejsce', verbose_name='Miejsce')),
            ],
            options={
                'verbose_name': 'Spotkanie czapkowe',
                'verbose_name_plural': 'Spotkania czapkowe',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Wyjazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data_rozpoczecia', models.DateField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia')),
                ('data_zakonczenia', models.DateField(default=django.utils.timezone.now, verbose_name='Data zakończenia')),
                ('typ', models.CharField(choices=[('AD', 'Adapciak'), ('KU', 'Kudłacze'), ('ZAGR', 'Zagraniczny')], max_length=10, verbose_name='Typ wyjazdu')),
                ('miejsce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.miejsce', verbose_name='Miejsce')),
                ('wydarzenia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wydarzenie', verbose_name='Wydarzenia')),
            ],
        ),
    ]
