# Generated by Django 5.2.1 on 2025-05-14 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrazwydarzenie',
            options={'ordering': ['-wydarzenie'], 'verbose_name': 'Zdjęcie z wydarzenia', 'verbose_name_plural': 'Zdjęcia z wydarzeń'},
        ),
    ]
