# Generated by Django 5.2.1 on 2025-07-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0002_delete_osoby_alter_zarzad_options_and_more"),
        ("kronika", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharakterystykaDzialanZarzadu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charakterystyka",
                    models.TextField(
                        blank=True,
                        verbose_name="Charakterystyka działań Zarządu",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.czlonek",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "dawny_zarzad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.dawnyzarzad",
                        verbose_name="Dawny Zarząd",
                    ),
                ),
                (
                    "zarzad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.zarzad",
                        verbose_name="Zarząd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charakterystyka działań Zarządu",
                "verbose_name_plural": "Charakterystyki działań Zarządów",
                "ordering": ["-zarzad"],
            },
        ),
    ]
