# Generated by Django 5.2 on 2025-05-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wyjazd',
            options={'ordering': ['-data_rozpoczecia'], 'verbose_name': 'Wyjazd', 'verbose_name_plural': 'Wyjazdy'},
        ),
        migrations.AddField(
            model_name='proces',
            name='opis',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='miejsce',
            name='typ',
            field=models.CharField(choices=[('Inny', 'Inny'), ('ObKult', 'Obiekt kultury'), ('Pub', 'Pub'), ('Szczyt', 'Szczyt')], max_length=10, verbose_name='Typ miejsca'),
        ),
    ]
