# Generated by Django 5.2 on 2025-05-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0002_alter_wyjazd_options_proces_opis_alter_miejsce_typ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proces',
        ),
        migrations.RemoveField(
            model_name='wyjazd',
            name='wydarzenia',
        ),
        migrations.RemoveField(
            model_name='wyjazd',
            name='miejsce',
        ),
        migrations.AlterField(
            model_name='miejsce',
            name='typ',
            field=models.CharField(choices=[('Inny', 'Inny'), ('ObKult', 'Obiekt kultury'), ('Pub', 'Pub'), ('Szczyt', 'Szczyt'), ('Uczel', 'Uczelnia')], max_length=10, verbose_name='Typ miejsca'),
        ),
        migrations.DeleteModel(
            name='SpotkanieCzapkowe',
        ),
        migrations.DeleteModel(
            name='Wydarzenie',
        ),
        migrations.DeleteModel(
            name='Wyjazd',
        ),
    ]
