# Generated by Django 5.2.1 on 2025-07-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0004_remove_bean_czapka_1_remove_bean_czapka_2_and_more"),
        (
            "kronika",
            "0003_alter_obrazzdarzenie_miejsce_alter_zdarzenie_miejsce_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="charakterystykadzialanzarzadu",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="osoby.czlonek",
                verbose_name="Autor",
            ),
        ),
    ]
