# Generated by Django 5.2 on 2025-05-01 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0003_delete_proces_remove_wyjazd_wydarzenia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Zdarzenie',
                'verbose_name_plural': 'Zdarzenia',
                'ordering': ['-data', 'nazwa'],
            },
        ),
        migrations.AlterField(
            model_name='miejsce',
            name='adres',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adres'),
        ),
        migrations.CreateModel(
            name='Wyjazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data_rozpoczecia', models.DateField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia')),
                ('data_zakonczenia', models.DateField(default=django.utils.timezone.now, verbose_name='Data zakończenia')),
                ('typ', models.CharField(choices=[('AD', 'Adapciak'), ('KU', 'Kudłacze'), ('ZAGR', 'Zagraniczny')], max_length=10, verbose_name='Typ wyjazdu')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('miejsce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.miejsce', verbose_name='Miejsce')),
                ('zdarzenia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.zdarzenie', verbose_name='Zdarzenia')),
            ],
            options={
                'verbose_name': 'Wyjazd',
                'verbose_name_plural': 'Wyjazdy',
                'ordering': ['-data_rozpoczecia'],
            },
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('typ', models.CharField(choices=[('I', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa'), ('Groby', 'Groby'), ('Ognisko', 'Ognisko'), ('OD', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyc', 'Wycieczka'), ('Wybory', 'Wybory'), ('UZ', 'Ułańskie Zdrowie')], max_length=10, verbose_name='Typ wydarzenia')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('miejsce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.miejsce', verbose_name='Miejsce')),
                ('zdarzenia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.zdarzenie', verbose_name='Zdarzenia')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Proces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('data_rozpoczecia', models.DateField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia')),
                ('data_zakonczenia', models.DateField(default=django.utils.timezone.now, verbose_name='Data zakończenia')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('zdarzenia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.zdarzenie', verbose_name='Zdarzenia')),
            ],
            options={
                'verbose_name': 'Proces',
                'verbose_name_plural': 'Procesy',
                'ordering': ['-data_rozpoczecia'],
            },
        ),
    ]
