# Generated by Django 5.2 on 2025-05-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('czlonkowie', '0014_innaosoba'),
        ('kronika', '0004_zdarzenie_alter_miejsce_adres_wyjazd_wydarzenie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='typ',
            field=models.CharField(choices=[('I', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa'), ('Groby', 'Groby'), ('H', 'Historyczne'), ('Ognisko', 'Ognisko'), ('OD', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyc', 'Wycieczka'), ('Wybory', 'Wybory'), ('UZ', 'Ułańskie Zdrowie')], max_length=10, verbose_name='Typ wydarzenia'),
        ),
        migrations.CreateModel(
            name='Uczestnictwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uczestnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Członek')),
            ],
            options={
                'verbose_name': 'Uczestnictwo',
                'verbose_name_plural': 'Uczestnictwo',
            },
        ),
    ]
