# Generated by Django 5.2 on 2025-05-04 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0014_innaosoba'),
        ('kronika', '0005_alter_wydarzenie_typ_uczestnictwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uczestnictwo',
            old_name='uczestnik',
            new_name='czlonek',
        ),
        migrations.AddField(
            model_name='uczestnictwo',
            name='inna_osoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.innaosoba', verbose_name='Inna osoba'),
        ),
    ]
