# Generated by Django 5.2 on 2025-05-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0006_rename_uczestnik_uczestnictwo_czlonek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='typ',
            field=models.CharField(choices=[('I', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa'), ('Groby', 'Groby'), ('H', 'Historyczne'), ('Ognisko', 'Ognisko'), ('OD', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyc', 'Wycieczka'), ('Wybory', 'Wybory'), ('UZ', 'Ułańskie Zdrowie'), ('Urocz', 'Uroczystości')], max_length=10, verbose_name='Typ wydarzenia'),
        ),
    ]
