# Generated by Django 5.2.1 on 2025-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0006_remove_wydarzenie_obrazy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypWydarzenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Typ wydarzenia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ wydarzenia",
                "verbose_name_plural": "Typy wydarzeń",
                "ordering": ["typ"],
            },
        ),
        migrations.CreateModel(
            name="TypWyjazdu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Typ wyjazdu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ wyjazdu",
                "verbose_name_plural": "Typy wyjazdów",
                "ordering": ["typ"],
            },
        ),
    ]
