# Generated by Django 5.2 on 2025-05-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0007_alter_wydarzenie_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miejsce',
            name='adres',
            field=models.CharField(blank=True, default='Ulica 1, Kraków, Polska', max_length=255, verbose_name='Adres'),
        ),
    ]
