# Generated by Django 5.2.1 on 2025-07-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0007_typwydarzenia_typwyjazdu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wydarzenie',
            old_name='typ_wydarzenia',
            new_name='old_typ_wydarzenia',
        ),
        migrations.RenameField(
            model_name='wydarzenie',
            old_name='typ_wyjazdu',
            new_name='old_typ_wyjazdu',
        ),
    ]
