# Generated by Django 5.2 on 2025-05-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0008_alter_miejsce_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='typ',
            field=models.CharField(choices=[('I', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa'), ('Groby', 'Groby'), ('H', 'Historyczne'), ('Ognisko', 'Ognisko'), ('OD', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Reakty', 'Reaktywacja'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyc', 'Wycieczka'), ('Wybory', 'Wybory'), ('UZ', 'Ułańskie Zdrowie'), ('Urocz', 'Uroczystości')], max_length=10, verbose_name='Typ wydarzenia'),
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='zdarzenia',
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='zdarzenia',
            field=models.ManyToManyField(blank=True, null=True, to='kronika.zdarzenie', verbose_name='Zdarzenia'),
        ),
    ]
