# Generated by Django 5.2 on 2025-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0009_alter_wydarzenie_typ_remove_wydarzenie_zdarzenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='zdarzenia',
            field=models.ManyToManyField(blank=True, to='kronika.zdarzenie', verbose_name='Zdarzenia'),
        ),
    ]
