# Generated by Django 5.2.1 on 2025-07-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0010_alter_wydarzenie_typ_wydarzenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdarzenie',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
