# Generated by Django 5.2 on 2025-05-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0015_alter_innaosoba_options_remove_innaosoba_imie_and_more'),
        ('kronika', '0010_alter_wydarzenie_zdarzenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrazWydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, max_length=100, verbose_name='Tytuł')),
                ('obraz', models.ImageField(upload_to='kronika/wydarzenia/', verbose_name='Dodaj obraz')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('inne_widoczne_osoby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.innaosoba', verbose_name='Inne widoczne osoby')),
                ('widoczni_czlonkowie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.czlonek', verbose_name='Widoczni członkowie')),
                ('wydarzenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wydarzenie', verbose_name='Wydarzenie')),
            ],
            options={
                'verbose_name': 'Zdjęcie z wydarzenia',
                'verbose_name_plural': 'Zdjęcia z wydarzeń',
                'ordering': ['-wydarzenie'],
            },
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='obrazy',
            field=models.ManyToManyField(blank=True, related_name='wydarzenie_obraz', to='kronika.obrazwydarzenie', verbose_name='Zdjęcia'),
        ),
    ]
