# Generated by Django 5.2 on 2025-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0011_obrazwydarzenie_wydarzenie_obrazy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miejsce',
            name='typ',
            field=models.CharField(choices=[('Inny', 'Inny'), ('ObKult', 'Obiekt kultury'), ('Pub', 'Pub/Klub'), ('Szczyt', 'Szczyt'), ('Uczel', 'Uczelnia')], max_length=10, verbose_name='Typ miejsca'),
        ),
        migrations.RemoveField(
            model_name='proces',
            name='zdarzenia',
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='typ',
            field=models.CharField(choices=[('I', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa'), ('Groby', 'Groby'), ('H', 'Historyczne'), ('Ognisko', 'Ognisko'), ('OD', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Reakty', 'Reaktywacja'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyc', 'Wycieczka'), ('Wybory', 'Wybory'), ('UZ', 'Ułańskie Zdrowie'), ('Urocz', 'Uroczystość'), ('ZS', 'Zawody sportowe')], max_length=10, verbose_name='Typ wydarzenia'),
        ),
        migrations.RemoveField(
            model_name='wyjazd',
            name='zdarzenia',
        ),
        migrations.AddField(
            model_name='proces',
            name='zdarzenia',
            field=models.ManyToManyField(blank=True, to='kronika.zdarzenie', verbose_name='Zdarzenia'),
        ),
        migrations.AddField(
            model_name='wyjazd',
            name='zdarzenia',
            field=models.ManyToManyField(blank=True, to='kronika.zdarzenie', verbose_name='Zdarzenia'),
        ),
    ]
