# Generated by Django 5.2.1 on 2025-07-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0011_alter_zdarzenie_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wydarzenie",
            old_name="czy_to_wyjazd",
            new_name="old_czy_to_wyjazd",
        ),
    ]
