# Generated by Django 5.2 on 2025-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0012_alter_miejsce_typ_remove_proces_zdarzenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miejsce',
            name='typ',
            field=models.CharField(choices=[('Inny', 'Inny'), ('Miasto', 'Miasto'), ('ObKult', 'Obiekt kultury'), ('Pub', 'Pub/Klub'), ('Szczyt', 'Szczyt'), ('Uczel', 'Uczelnia')], max_length=10, verbose_name='Typ miejsca'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='typ',
            field=models.CharField(choices=[('Akcja', 'Akcja'), ('Inne', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa/wykład/prelekcja'), ('Groby', 'Groby'), ('Hist', 'Historyczne'), ('Ognisko', 'Grill/Ognisko'), ('Ostry', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Reakty', 'Reaktywacja'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyciecz', 'Wycieczka'), ('Wybory', 'Wybory'), ('Ulanskie', 'Ułańskie Zdrowie'), ('Urocz', 'Uroczystość'), ('ZawodySp', 'Zawody sportowe')], max_length=10, verbose_name='Typ wydarzenia'),
        ),
    ]
