# Generated by Django 5.2.1 on 2025-07-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0013_wydarzenie_czy_to_wyjazd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wydarzenie",
            name="old_czy_to_wyjazd",
        ),
    ]
