# Generated by Django 5.2 on 2025-05-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czlonkowie', '0019_alter_bean_pewnosc_stazu_alter_bean_staz'),
        ('kronika', '0013_alter_miejsce_typ_alter_wydarzenie_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczestnictwo',
            name='bean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='czlonkowie.bean', verbose_name='Bean'),
        ),
    ]
