# Generated by Django 5.2.1 on 2025-07-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0014_remove_wydarzenie_old_czy_to_wyjazd'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='czy_jednodniowe',
            field=models.BooleanField(default=True, verbose_name='Jednodniowe'),
        ),
    ]
