# Generated by Django 5.2 on 2025-05-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0014_uczestnictwo_bean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrazwydarzenie',
            name='inne_widoczne_osoby',
        ),
        migrations.RemoveField(
            model_name='obrazwydarzenie',
            name='widoczni_czlonkowie',
        ),
    ]
