# Generated by Django 5.2.1 on 2025-07-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0018_alter_pojecie_wydarzenie_and_more"),
        ("kronika", "0015_wydarzenie_czy_jednodniowe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="miejsce",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="widoczne_osoby",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="zdarzenie",
        ),
        migrations.RemoveField(
            model_name="proces",
            name="zdarzenia",
        ),
        migrations.RemoveField(
            model_name="wydarzenie",
            name="typ_wydarzenia",
        ),
        migrations.RemoveField(
            model_name="wydarzenie",
            name="typ_wyjazdu",
        ),
        migrations.RemoveField(
            model_name="wydarzenie",
            name="miejsca",
        ),
        migrations.RemoveField(
            model_name="wydarzenie",
            name="uczestnicy",
        ),
        migrations.RemoveField(
            model_name="zdarzenie",
            name="wydarzenie",
        ),
        migrations.RemoveField(
            model_name="zdarzenie",
            name="miejsce",
        ),
        migrations.RemoveField(
            model_name="zdarzenie",
            name="powiazane_osoby",
        ),
        migrations.DeleteModel(
            name="ObrazWydarzenie",
        ),
        migrations.DeleteModel(
            name="ObrazZdarzenie",
        ),
        migrations.DeleteModel(
            name="Proces",
        ),
        migrations.DeleteModel(
            name="TypWydarzenia",
        ),
        migrations.DeleteModel(
            name="TypWyjazdu",
        ),
        migrations.DeleteModel(
            name="Wydarzenie",
        ),
        migrations.DeleteModel(
            name="Zdarzenie",
        ),
    ]
