# Generated by Django 5.2 on 2025-05-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('czlonkowie', '0019_alter_bean_pewnosc_stazu_alter_bean_staz'),
        ('kronika', '0015_remove_obrazwydarzenie_inne_widoczne_osoby_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uczestnictwo',
            new_name='Osoby',
        ),
        migrations.AlterModelOptions(
            name='osoby',
            options={'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
    ]
