# Generated by Django 5.2.1 on 2025-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0002_alter_obrazwydarzenie_options_wyjazd'),
        ('kronika', '0016_rename_uczestnictwo_osoby_alter_osoby_options'),
    ]

    operations = [
    ]
