# Generated by Django 5.2.1 on 2025-07-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0016_remove_obrazzdarzenie_miejsce_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypWydarzeniaHistorycznego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        max_length=40,
                        verbose_name="Typ wydarzenia historycznego",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ wydarzenia historycznego",
                "verbose_name_plural": "Typy wydarzeń historycznych",
                "ordering": ["typ"],
            },
        ),
        migrations.CreateModel(
            name="WydarzenieHistoryczne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=100, verbose_name="Nazwa"),
                ),
                ("data", models.DateField(blank=True, verbose_name="Data")),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "typ",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kronika.typwydarzeniahistorycznego",
                        verbose_name="Typ wydarzenia historycznego",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydarzenie historyczne",
                "verbose_name_plural": "Wydarzenia historyczne",
                "ordering": ["nazwa"],
            },
        ),
    ]
