# Generated by Django 5.2.1 on 2025-07-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0017_typwydarzeniahistorycznego_wydarzeniehistoryczne"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wydarzeniehistoryczne",
            name="data",
            field=models.DateField(blank=True, null=True, verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="wydarzeniehistoryczne",
            name="opis",
            field=models.TextField(blank=True, null=True, verbose_name="Opis"),
        ),
        migrations.CreateModel(
            name="Kadencja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lata",
                    models.IntegerField(
                        choices=[
                            (2009, "2009/2010"),
                            (2010, "2010/2011"),
                            (2011, "2011/2012"),
                            (2012, "2012/2013"),
                            (2013, "2013/2014"),
                            (2014, "2014/2015"),
                            (2015, "2015/2016"),
                            (2016, "2016/2017"),
                            (2017, "2017/2018"),
                            (2018, "2018/2019"),
                            (2019, "2019/2020"),
                            (2020, "2020/2021"),
                            (2021, "2021/2022"),
                            (2022, "2022/2023"),
                            (2023, "2023/2024"),
                            (2024, "2024/2025"),
                            (2025, "2025/2026"),
                        ],
                        verbose_name="Lata",
                    ),
                ),
                (
                    "rozpoczecie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rozpoczyna_kadencje",
                        to="kronika.wydarzeniehistoryczne",
                        verbose_name="Rozpoczęcie kadencji",
                    ),
                ),
                (
                    "zakonczenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="konczy_kadencje",
                        to="kronika.wydarzeniehistoryczne",
                        verbose_name="Zakończenie kadencji",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kadencja",
                "verbose_name_plural": "Kadencje",
                "ordering": ["lata"],
            },
        ),
    ]
