# Generated by Django 5.2.1 on 2025-05-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0017_merge_20250514_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Osoby',
        ),
    ]
