# Generated by Django 5.2.1 on 2025-05-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0018_delete_osoby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wyjazd',
        ),
    ]
