# Generated by Django 5.2.1 on 2025-07-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0019_wydarzeniehistoryczne_wydarzenie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charakterystykadzialanzarzadu",
            options={
                "verbose_name": "Charakterystyka działań Zarządu",
                "verbose_name_plural": "Charakterystyki działań Zarządów",
            },
        ),
        migrations.RemoveField(
            model_name="charakterystykadzialanzarzadu",
            name="dawny_zarzad",
        ),
        migrations.RemoveField(
            model_name="charakterystykadzialanzarzadu",
            name="zarzad",
        ),
    ]
