# Generated by Django 5.2.1 on 2025-05-14 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0019_delete_wyjazd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydarzenie',
            options={'ordering': ['-data_rozpoczecia'], 'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='data',
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='miejsce',
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='typ',
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='czy_to_wyjazd',
            field=models.CharField(choices=[('T', 'Tak'), ('N', 'Nie')], default='N', max_length=1, verbose_name='Czy to wyjazd?'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='data_rozpoczecia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='data_zakonczenia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data zakończenia'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='miejsca',
            field=models.ManyToManyField(blank=True, to='kronika.miejsce', verbose_name='Miejsce'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='typ_wydarzenia',
            field=models.CharField(choices=[('Akcja', 'Akcja'), ('Inne', 'Inne'), ('Karczma', 'Karczma'), ('Kino', 'Kino'), ('KonfNauk', 'Konferencja naukowa/wykład/prelekcja'), ('Groby', 'Groby'), ('Hist', 'Historyczne'), ('Ognisko', 'Grill/Ognisko'), ('Ostry', 'Ostry Dyżur'), ('Plansz', 'Planszówki'), ('Reakty', 'Reaktywacja'), ('Teatr', 'Teatr'), ('Walne', 'Walne'), ('Wyciecz', 'Wycieczka'), ('Wybory', 'Wybory'), ('Ulanskie', 'Ułańskie Zdrowie'), ('Urocz', 'Uroczystość'), ('ZawodySp', 'Zawody sportowe'), ('n/a', 'Nie dotyczy')], default='n/a', max_length=10, verbose_name='Typ wydarzenia'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='typ_wyjazdu',
            field=models.CharField(choices=[('Adapciak', 'Adapciak'), ('Inny', 'Inny'), ('Kudlacze', 'Kudłacze'), ('ZAGR', 'Zagraniczny'), ('n/a', 'Nie dotyczy')], default='n/a', max_length=10, verbose_name='Typ wyjazdu'),
        ),
    ]
