# Generated by Django 5.2.1 on 2025-07-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kronika",
            "0020_alter_charakterystykadzialanzarzadu_options_and_more",
        ),
        ("osoby", "0021_remove_halloffame_bean_remove_halloffame_czlonek"),
    ]

    operations = [
        migrations.AddField(
            model_name="charakterystykadzialanzarzadu",
            name="zarzad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charakterystyki",
                to="osoby.zarzad",
                verbose_name="Zarząd",
            ),
        ),
    ]
