# Generated by Django 5.2.1 on 2025-05-14 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0020_alter_wydarzenie_options_remove_wydarzenie_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrazZdarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, max_length=100, verbose_name='Tytuł')),
                ('data', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data wykonania')),
                ('obraz', models.ImageField(upload_to='kronika/zdarzenia/', verbose_name='Dodaj obraz')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('miejsce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.miejsce', verbose_name='Miejsce')),
                ('zdarzenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.zdarzenie', verbose_name='Zdarzenie')),
            ],
            options={
                'verbose_name': 'Zdjęcie ze zdarzenia',
                'verbose_name_plural': 'Zdjęcia ze zdarzeń',
                'ordering': ['-data'],
            },
        ),
    ]
