# Generated by Django 5.2.1 on 2025-05-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0021_obrazzdarzenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdarzenie',
            name='miejsce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.miejsce', verbose_name='Miejsce'),
        ),
        migrations.AddField(
            model_name='zdarzenie',
            name='obrazy',
            field=models.ManyToManyField(blank=True, related_query_name='zdarzenie_obrazy', to='kronika.obrazzdarzenie', verbose_name='Zdjęcia'),
        ),
    ]
