# Generated by Django 5.2.1 on 2025-07-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0021_charakterystykadzialanzarzadu_zarzad"),
        ("osoby", "0021_remove_halloffame_bean_remove_halloffame_czlonek"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charakterystykadzialanzarzadu",
            options={
                "ordering": ["-zarzad"],
                "verbose_name": "Charakterystyka działań Zarządu",
                "verbose_name_plural": "Charakterystyki działań Zarządów",
            },
        ),
        migrations.AlterField(
            model_name="charakterystykadzialanzarzadu",
            name="zarzad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charakterystyki",
                to="osoby.zarzad",
                verbose_name="Zarząd",
            ),
        ),
    ]
