# Generated by Django 5.2.1 on 2025-07-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0022_alter_charakterystykadzialanzarzadu_options_and_more"),
        ("osoby", "0021_remove_halloffame_bean_remove_halloffame_czlonek"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CharakterystykaDzialanZarzadu",
            new_name="PodsumowanieKadencji",
        ),
    ]
