# Generated by Django 5.2.1 on 2025-05-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0022_zdarzenie_miejsce_zdarzenie_obrazy'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdarzenie',
            name='wydarzenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kronika.wydarzenie', verbose_name='Wydarzenie'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='zdarzenia',
            field=models.ManyToManyField(blank=True, related_name='wydarzenie_zdarzenia', to='kronika.zdarzenie', verbose_name='Zdarzenia'),
        ),
    ]
