# Generated by Django 5.2.1 on 2025-07-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kronika",
            "0023_rename_charakterystykadzialanzarzadu_podsumowaniekadencji",
        ),
        ("osoby", "0021_remove_halloffame_bean_remove_halloffame_czlonek"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podsumowaniekadencji",
            options={
                "ordering": ["-zarzad"],
                "verbose_name": "Podsumowanie kadencji",
                "verbose_name_plural": "Podsumowania kadencji",
            },
        ),
        migrations.RemoveField(
            model_name="podsumowaniekadencji",
            name="charakterystyka",
        ),
        migrations.AddField(
            model_name="podsumowaniekadencji",
            name="podsumowanie",
            field=models.TextField(
                blank=True, verbose_name="Podsumowanie kadencji"
            ),
        ),
        migrations.AlterField(
            model_name="podsumowaniekadencji",
            name="zarzad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podsumowania_kadencji",
                to="osoby.zarzad",
                verbose_name="Zarząd",
            ),
        ),
    ]
