# Generated by Django 5.2.1 on 2025-05-14 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0023_zdarzenie_wydarzenie_alter_wydarzenie_zdarzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wydarzenie',
            name='zdarzenia',
        ),
        migrations.RemoveField(
            model_name='zdarzenie',
            name='obrazy',
        ),
        migrations.AlterField(
            model_name='zdarzenie',
            name='wydarzenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zdarzenia', to='kronika.wydarzenie', verbose_name='Wydarzenie'),
        ),
    ]
