# Generated by Django 5.2.1 on 2025-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0024_remove_wydarzenie_zdarzenia_remove_zdarzenie_obrazy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link do wydarzenia na FB'),
        ),
    ]
