# Generated by Django 5.2.1 on 2025-07-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0024_alter_podsumowaniekadencji_options_and_more"),
        ("osoby", "0021_remove_halloffame_bean_remove_halloffame_czlonek"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZadanieChrzcielne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=40, verbose_name="Nazwa krótka")),
                ("opis", models.TextField(blank=True, null=True, verbose_name="Opis")),
                (
                    "zalacznik",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdfs/",
                        verbose_name="Załącznik",
                    ),
                ),
                (
                    "zdjecia",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Zdjęcia",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Link")),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.czlonek",
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie chrzcielne",
                "verbose_name_plural": "Zadania chrzcielne",
                "ordering": ["nazwa"],
            },
        ),
    ]
