# Generated by Django 5.2.1 on 2025-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronika', '0025_wydarzenie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdarzenie',
            name='godzina',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina'),
        ),
        migrations.AlterField(
            model_name='miejsce',
            name='typ',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Mleczny', 'Bar mleczny'), ('Inny', 'Inny'), ('Karaoke', 'Karaoke'), ('Kino', 'Kino'), ('Lokum', 'Lokum'), ('Miasto', 'Miasto'), ('ObKult', 'Obiekt kultury'), ('OgrodPlac', 'Ogród/Plac'), ('Pub', 'Pub/Klub'), ('Restaur', 'Restauracja'), ('Schronisko', 'Schronisko'), ('Szczyt', 'Szczyt'), ('Teatr', 'Teatr'), ('Uczel', 'Uczelnia')], max_length=10, verbose_name='Typ miejsca'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='miejsca',
            field=models.ManyToManyField(blank=True, to='kronika.miejsce', verbose_name='Miejsca'),
        ),
    ]
