# Generated by Django 5.2.1 on 2025-07-28 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0025_zadaniechrzcielne"),
        ("osoby", "0021_remove_halloffame_bean_remove_halloffame_czlonek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zadaniechrzcielne",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zadanie_chrzcielne",
                to="osoby.czlonek",
                verbose_name="Autor",
            ),
        ),
    ]
