# Generated by Django 5.2.1 on 2025-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0026_alter_zadaniechrzcielne_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zadaniechrzcielne",
            name="zalacznik",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdfs/",
                verbose_name="Załącznik (pdf)",
            ),
        ),
    ]
