# Generated by Django 5.2.1 on 2025-08-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kalendarz",
            "0005_alter_wydarzeniekalendarzowe_data_rozpoczecia_and_more",
        ),
        ("kronika", "0027_alter_zadaniechrzcielne_zalacznik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wydarzeniehistoryczne",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="powiazane_wydarzenie_historyczne",
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Powiązane wydarzenie z kalendarza",
            ),
        ),
    ]
