# Generated by Django 5.2.1 on 2025-08-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encyklopedia", "0032_alter_pojecie_wydarzenie_and_more"),
        ("kronika", "0028_alter_wydarzeniehistoryczne_wydarzenie"),
        ("zrodla", "0011_alter_edykt_numer_alter_ukaz_numer"),
    ]

    operations = [
        migrations.AddField(
            model_name="wydarzeniehistoryczne",
            name="dokument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.dokument",
                verbose_name="Powiązany dokument",
            ),
        ),
        migrations.AddField(
            model_name="wydarzeniehistoryczne",
            name="pojecie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="encyklopedia.pojecie",
                verbose_name="Link do pojęcia ze słownika",
            ),
        ),
    ]
