# Generated by Django 5.2.1 on 2025-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0029_wydarzeniehistoryczne_dokument_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wydarzeniehistoryczne",
            name="data",
        ),
    ]
