# Generated by Django 5.2.1 on 2025-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0030_remove_wydarzeniehistoryczne_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="wydarzeniehistoryczne",
            name="data_przyblizona",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Data przybliżona",
            ),
        ),
    ]
