# Generated by Django 5.2.1 on 2025-08-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0031_wydarzeniehistoryczne_data_przyblizona"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wydarzeniehistoryczne",
            options={
                "ordering": ["-wydarzenie__data_rozpoczecia", "-data_przyblizona"],
                "verbose_name": "Wydarzenie historyczne",
                "verbose_name_plural": "Wydarzenia historyczne",
            },
        ),
        migrations.AddField(
            model_name="wydarzeniehistoryczne",
            name="typy",
            field=models.ManyToManyField(
                blank=True,
                to="kronika.typwydarzeniahistorycznego",
                verbose_name="Typ wydarzenia historycznego",
            ),
        ),
        migrations.AlterField(
            model_name="wydarzeniehistoryczne",
            name="typ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wydarzenia_tego_typu",
                to="kronika.typwydarzeniahistorycznego",
                verbose_name="Typ wydarzenia historycznego",
            ),
        ),
    ]
