# Generated by Django 5.2.1 on 2025-08-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0032_alter_wydarzeniehistoryczne_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wydarzeniehistoryczne",
            name="typ",
        ),
    ]
