# Generated by Django 5.2.1 on 2025-08-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0033_remove_wydarzeniehistoryczne_typ"),
    ]

    operations = [
        migrations.CreateModel(
            name="KategoriaZadaniaChrzcielnego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=100, verbose_name="Nazwa"),
                ),
            ],
            options={
                "verbose_name": "Kategoria zadania chrzcielnego",
                "verbose_name_plural": "Kategorie zadań chrzcielnych",
                "ordering": ["nazwa"],
            },
        ),
        migrations.AlterModelOptions(
            name="zadaniechrzcielne",
            options={
                "ordering": ["-autor__depositio_beanorum__data_rozpoczecia"],
                "verbose_name": "Zadanie chrzcielne",
                "verbose_name_plural": "Zadania chrzcielne",
            },
        ),
        migrations.AddField(
            model_name="zadaniechrzcielne",
            name="kategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kronika.kategoriazadaniachrzcielnego",
                verbose_name="Kategoria",
            ),
        ),
    ]
