# Generated by Django 5.2.1 on 2025-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0034_kategoriazadaniachrzcielnego_and_more"),
        ("osoby", "0031_alter_byt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zadaniechrzcielne",
            options={
                "ordering": ["-autorzy__depositio_beanorum__data_rozpoczecia"],
                "verbose_name": "Zadanie chrzcielne",
                "verbose_name_plural": "Zadania chrzcielne",
            },
        ),
        migrations.RemoveField(
            model_name="zadaniechrzcielne",
            name="autor",
        ),
        migrations.AddField(
            model_name="zadaniechrzcielne",
            name="autorzy",
            field=models.ManyToManyField(
                blank=True, to="osoby.czlonek", verbose_name="Autorzy"
            ),
        ),
    ]
