# Generated by Django 5.2.1 on 2025-08-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0035_alter_zadaniechrzcielne_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zadaniechrzcielne",
            options={
                "verbose_name": "Zadanie chrzcielne",
                "verbose_name_plural": "Zadania chrzcielne",
            },
        ),
    ]
