# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0036_alter_zadaniechrzcielne_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="kadencja",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="kategoriazadaniachrzcielnego",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="podsumowaniekadencji",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="typwydarzeniahistorycznego",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="wydarzeniehistoryczne",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="zadaniechrzcielne",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
