# Generated by Django 5.2.1 on 2025-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0041_remove_kadencja_fields_positions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kadencja",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="kategoriazadaniachrzcielnego",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="podsumowaniekadencji",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="typwydarzeniahistorycznego",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="wydarzeniehistoryczne",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="zadaniechrzcielne",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
