# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0042_kadencja_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kadencja",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="kategoriazadaniachrzcielnego",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="podsumowaniekadencji",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="typwydarzeniahistorycznego",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="wydarzeniehistoryczne",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="zadaniechrzcielne",
            name="search_text",
        ),
    ]
