# Generated by Django 5.2.1 on 2025-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0045_alter_kadencja_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wydarzeniehistoryczne",
            name="pojecie",
        ),
        migrations.AlterField(
            model_name="wydarzeniehistoryczne",
            name="data_przyblizona",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Data przybliżona (jeśli znana, zostaw puste)",
            ),
        ),
    ]
