# Generated by Django 5.2.1 on 2025-08-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("osoby", "0039_komisjarewizyjna_delete_komisjarewizyjna1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Odznaczenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=255, verbose_name="Nazwa"),
                ),
                ("opis", models.TextField(verbose_name="Opis")),
                (
                    "rok_powstania",
                    models.IntegerField(
                        blank=True, verbose_name="Rok powstania"
                    ),
                ),
                (
                    "fundatorzy",
                    models.ManyToManyField(
                        blank=True, to="osoby.byt", verbose_name="Fundatorzy"
                    ),
                ),
            ],
            options={
                "verbose_name": "Odznaczenie",
                "verbose_name_plural": "Odznaczenia",
                "ordering": ["nazwa"],
            },
        ),
    ]
