# Generated by Django 5.2.1 on 2025-08-30 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0001_initial"),
        ("zrodla", "0019_uchwala_walne"),
    ]

    operations = [
        migrations.AddField(
            model_name="odznaczenie",
            name="dokument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.dokument",
                verbose_name="Dokument",
            ),
        ),
    ]
