# Generated by Django 5.2.1 on 2025-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0002_odznaczenie_dokument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odznaczenie",
            name="opis",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
    ]
