# Generated by Django 5.2.1 on 2025-08-30 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0004_alter_odznaczenie_rok_powstania"),
        ("osoby", "0039_komisjarewizyjna_delete_komisjarewizyjna1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nagrodzeni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data wręczenia odznaczenia",
                    ),
                ),
                (
                    "zaslugi",
                    models.TextField(blank=True, verbose_name="Zasługi"),
                ),
                (
                    "odznaczenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="honory.odznaczenie",
                        verbose_name="Odznaczenie",
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.byt",
                        verbose_name="Osoba/organizacja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nagrodzeni",
                "verbose_name_plural": "Nagrodzeni",
                "ordering": ["-data", "osoba"],
            },
        ),
    ]
