# Generated by Django 5.2.1 on 2025-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0005_nagrodzeni"),
    ]

    operations = [
        migrations.AddField(
            model_name="odznaczenie",
            name="zarzad_funduje",
            field=models.BooleanField(
                default=False, verbose_name="Zarząd funduje"
            ),
        ),
    ]
