# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0006_odznaczenie_zarzad_funduje"),
    ]

    operations = [
        migrations.AddField(
            model_name="nagrodzeni",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="odznaczenie",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
