# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0010_nagrodzeni_search_dict_odznaczenie_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nagrodzeni",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="nagrodzeni",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="odznaczenie",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="odznaczenie",
            name="search_dict",
        ),
    ]
