# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0012_nagrodzeni_search_dict_odznaczenie_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nagrodzeni",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="odznaczenie",
            name="search_text",
        ),
    ]
