# Generated by Django 5.2.1 on 2025-09-12 13:55

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0013_remove_nagrodzeni_search_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nagrodzeni",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="odznaczenie",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
