# Generated by Django 5.2.1 on 2025-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honory", "0014_nagrodzeni_simple_tsv_odznaczenie_simple_tsv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nagrodzeni",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="odznaczenie",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
