# Generated by Django 5.2.1 on 2025-07-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("osoby", "0011_alter_bean_pewnosc_stazu_alter_czlonek_imie_piwne_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=255, verbose_name="Tytuł")),
                (
                    "data",
                    models.DateField(auto_now_add=True, verbose_name="Data wydania"),
                ),
                (
                    "streszczenie",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Streszczenie"
                    ),
                ),
                ("tekst", models.TextField(blank=True, verbose_name="Tekst")),
                (
                    "autorzy",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wydane_dokumenty",
                        to="osoby.osoba",
                        verbose_name="Autorzy",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumenty",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Edykt",
            fields=[
                (
                    "dokument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dokumenty.dokument",
                    ),
                ),
                ("numer", models.IntegerField(blank=True, verbose_name="Numer")),
            ],
            options={
                "verbose_name": "Edykt",
                "verbose_name_plural": "Edykty",
                "ordering": ["-numer"],
            },
            bases=("dokumenty.dokument",),
        ),
        migrations.CreateModel(
            name="Ukaz",
            fields=[
                (
                    "dokument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dokumenty.dokument",
                    ),
                ),
                ("numer", models.IntegerField(blank=True, verbose_name="Numer")),
            ],
            options={
                "verbose_name": "Ukaz",
                "verbose_name_plural": "Ukazy",
                "ordering": ["-numer"],
            },
            bases=("dokumenty.dokument",),
        ),
    ]
