# Generated by Django 5.2.1 on 2025-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokumenty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="tekst",
        ),
        migrations.AddField(
            model_name="dokument",
            name="plik",
            field=models.FileField(blank=True, upload_to="pdfs/", verbose_name="Tekst"),
        ),
    ]
