# Generated by Django 5.2.1 on 2025-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokumenty", "0002_remove_dokument_tekst_dokument_plik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokument",
            name="streszczenie",
            field=models.TextField(blank=True, verbose_name="Streszczenie"),
        ),
    ]
