# Generated by Django 5.2.1 on 2025-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokumenty", "0003_alter_dokument_streszczenie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokument",
            name="data",
            field=models.DateField(blank=True, verbose_name="Data wydania"),
        ),
    ]
