# Generated by Django 5.2.1 on 2025-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
        ("zrodla", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zrodlo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nazwa"
                    ),
                ),
                (
                    "zawartosc",
                    models.TextField(blank=True, verbose_name="Zawartość"),
                ),
                ("link", models.URLField(blank=True, verbose_name="Link")),
                (
                    "gdzie_znalezc",
                    models.TextField(blank=True, verbose_name="Gdzie znaleźć"),
                ),
                (
                    "autorzy",
                    models.ManyToManyField(
                        blank=True, to="osoby.osoba", verbose_name="Autorzy"
                    ),
                ),
            ],
            options={
                "verbose_name": "Źródło",
                "verbose_name_plural": "Źródła",
                "ordering": ("nazwa",),
            },
        ),
    ]
