# Generated by Django 5.2.1 on 2025-07-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
        ("zrodla", "0002_zrodlo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Zrodlo",
            new_name="ZrodloOgolne",
        ),
    ]
