# Generated by Django 5.2.1 on 2025-07-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
        ("zrodla", "0003_rename_zrodlo_zrodloogolne"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zrodlo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tytul",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tytuł"
                    ),
                ),
                (
                    "zawartosc",
                    models.TextField(blank=True, verbose_name="Zawartość"),
                ),
                (
                    "autorzy",
                    models.ManyToManyField(
                        blank=True, to="osoby.osoba", verbose_name="Autorzy"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Źródło",
                "verbose_name_plural": "Źródła",
                "ordering": ("tytul",),
            },
        ),
    ]
