# Generated by Django 5.2.1 on 2025-07-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0004_zrodlo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zrodloogolne",
            options={
                "ordering": ("tytul",),
                "verbose_name": "Źródło",
                "verbose_name_plural": "Źródła różne",
            },
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="autorzy",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="id",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="nazwa",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="zawartosc",
        ),
        migrations.AddField(
            model_name="zrodloogolne",
            name="zrodlo_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="zrodla.zrodlo",
            ),
            preserve_default=False,
        ),
    ]
