# Generated by Django 5.2.1 on 2025-07-26 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0012_alter_dawnyzarzad_kadencja_alter_zarzad_kadencja"),
        ("zrodla", "0005_alter_zrodloogolne_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="autorzy",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="id",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="tytul",
        ),
        migrations.RemoveField(
            model_name="zrodlo",
            name="zawartosc",
        ),
        migrations.AddField(
            model_name="dokument",
            name="zrodlo_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="zrodla.zrodlo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zrodloogolne",
            name="zawartosc",
            field=models.TextField(blank=True, verbose_name="Zawartość"),
        ),
        migrations.AlterField(
            model_name="zrodlo",
            name="autorzy",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_ktorych_jest_autorem",
                to="osoby.osoba",
                verbose_name="Autorzy",
            ),
        ),
    ]
