# Generated by Django 5.2.1 on 2025-07-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0006_remove_dokument_autorzy_remove_dokument_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="plik",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="link",
        ),
        migrations.AddField(
            model_name="zrodlo",
            name="plik",
            field=models.FileField(
                blank=True, upload_to="pdfs/", verbose_name="Tekst"
            ),
        ),
    ]
