# Generated by Django 5.2.1 on 2025-07-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0007_remove_dokument_plik_remove_zrodloogolne_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zrodlo",
            name="plik",
            field=models.FileField(blank=True, upload_to="pdfs/", verbose_name="Plik"),
        ),
    ]
