# Generated by Django 5.2.1 on 2025-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0008_alter_zrodlo_plik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokument",
            name="streszczenie",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="Streszczenie"
            ),
        ),
        migrations.AlterField(
            model_name="zrodlo",
            name="tytul",
            field=models.CharField(max_length=255, verbose_name="Tytuł"),
        ),
    ]
