# Generated by Django 5.2.1 on 2025-07-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0009_alter_dokument_streszczenie_alter_zrodlo_tytul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokument",
            name="data",
            field=models.DateField(blank=True, null=True, verbose_name="Data wydania"),
        ),
    ]
