# Generated by Django 5.2.1 on 2025-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0010_alter_dokument_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edykt",
            name="numer",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numer"
            ),
        ),
        migrations.AlterField(
            model_name="ukaz",
            name="numer",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numer"
            ),
        ),
    ]
