# Generated by Django 5.2.1 on 2025-08-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0029_alter_zarzad_options"),
        ("zrodla", "0011_alter_edykt_numer_alter_ukaz_numer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zrodlo",
            name="autorzy",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_ktorych_jest_autorem",
                to="osoby.byt",
                verbose_name="Autorzy",
            ),
        ),
    ]
