# Generated by Django 5.2.1 on 2025-08-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0012_alter_zrodlo_autorzy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oswiadczenie",
            fields=[
                (
                    "dokument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="zrodla.dokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oświadczenie",
                "verbose_name_plural": "Oświadczenia",
                "ordering": ["-data"],
            },
            bases=("zrodla.dokument",),
        ),
    ]
