# Generated by Django 5.2.1 on 2025-08-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skarbiec", "0004_transakcja_tytul"),
        ("zrodla", "0013_oswiadczenie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rozliczenie",
            fields=[
                (
                    "dokument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="zrodla.dokument",
                    ),
                ),
                (
                    "transakcja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="skarbiec.transakcja",
                        verbose_name="Transakcja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rozliczenie",
                "verbose_name_plural": "Rozliczenia",
                "ordering": ["-data"],
            },
            bases=("zrodla.dokument",),
        ),
    ]
