# Generated by Django 5.2.1 on 2025-08-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0014_rozliczenie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rozliczenie",
            name="transakcja",
        ),
    ]
