# Generated by Django 5.2.1 on 2025-08-29 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osoby", "0036_alter_organizacjastudencka_options_and_more"),
        ("zrodla", "0015_remove_rozliczenie_transakcja"),
    ]

    operations = [
        migrations.CreateModel(
            name="Korespondencja",
            fields=[
                (
                    "dokument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="zrodla.dokument",
                    ),
                ),
                (
                    "adresaci",
                    models.ManyToManyField(
                        blank=True, to="osoby.byt", verbose_name="Adresaci"
                    ),
                ),
            ],
            options={
                "verbose_name": "Korespondencyj",
                "verbose_name_plural": "Korespondencyj",
                "ordering": ["data"],
            },
            bases=("zrodla.dokument",),
        ),
    ]
