# Generated by Django 5.2.1 on 2025-08-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0016_korespondencja"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="korespondencja",
            options={
                "ordering": ["data"],
                "verbose_name": "Korespondencja",
                "verbose_name_plural": "Korespondencja",
            },
        ),
    ]
