# Generated by Django 5.2.1 on 2025-08-29 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kronika", "0036_alter_zadaniechrzcielne_options"),
        ("zrodla", "0018_uchwala"),
    ]

    operations = [
        migrations.AddField(
            model_name="uchwala",
            name="walne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kronika.wydarzeniehistoryczne",
                verbose_name="Walne",
            ),
        ),
    ]
