# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0019_uchwala_walne"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="zrodloogolne",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
