# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0020_dokument_search_text_zrodloogolne_search_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="zrodloogolne",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
