# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0023_dokument_search_dict_zrodloogolne_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="search_dict",
        ),
    ]
