# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0025_dokument_search_dict_zrodloogolne_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="search_text",
        ),
    ]
