# Generated by Django 5.2.1 on 2025-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0026_remove_dokument_search_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="extracted_text",
            field=models.TextField(blank=True, verbose_name="Tekst z pdfa"),
        ),
        migrations.AddField(
            model_name="zrodloogolne",
            name="extracted_text",
            field=models.TextField(blank=True, verbose_name="Tekst z pdfa"),
        ),
    ]
