# Generated by Django 5.2.1 on 2025-09-11 10:43

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0027_dokument_extracted_text_zrodloogolne_extracted_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="zrodloogolne",
            name="tsv",
        ),
        migrations.AddField(
            model_name="zrodlo",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="zrodlo",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
