# Generated by Django 5.2.1 on 2025-09-12 13:55

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "zrodla",
            "0028_remove_dokument_search_dict_remove_dokument_tsv_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zrodlo",
            name="simple_tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
