# Generated by Django 5.2.1 on 2025-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0030_alter_zrodlo_search_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="KategoriaEdyktu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategoria",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kategoria edyktu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria edyktu",
                "verbose_name_plural": "Kategorie edyktów",
                "ordering": ["kategoria"],
            },
        ),
        migrations.CreateModel(
            name="KategoriaUkazu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategoria",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kategoria ukazu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria ukazu",
                "verbose_name_plural": "Kategorie ukazów",
                "ordering": ["kategoria"],
            },
        ),
    ]
