# Generated by Django 5.2.1 on 2025-10-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0031_kategoriaedyktu_kategoriaukazu"),
    ]

    operations = [
        migrations.AddField(
            model_name="edykt",
            name="kategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.kategoriaedyktu",
                verbose_name="Kategoria",
            ),
        ),
        migrations.AddField(
            model_name="ukaz",
            name="kategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.kategoriaukazu",
                verbose_name="Kategoria",
            ),
        ),
    ]
