# Generated by Django 5.2.1 on 2025-10-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0032_edykt_kategoria_ukaz_kategoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edykt",
            name="kategoria",
        ),
        migrations.RemoveField(
            model_name="ukaz",
            name="kategoria",
        ),
    ]
