# Generated by Django 5.2.1 on 2025-10-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0033_remove_edykt_kategoria_remove_ukaz_kategoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="edykt",
            name="kategorie",
            field=models.ManyToManyField(
                blank=True, to="zrodla.kategoriaedyktu", verbose_name="Kategoria"
            ),
        ),
        migrations.AddField(
            model_name="ukaz",
            name="kategorie",
            field=models.ManyToManyField(
                blank=True, to="zrodla.kategoriaukazu", verbose_name="Kategoria"
            ),
        ),
    ]
