# Generated by Django 5.2.1 on 2025-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0034_edykt_kategorie_ukaz_kategorie"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KategoriaEdyktu",
        ),
        migrations.AlterField(
            model_name="edykt",
            name="kategorie",
            field=models.ManyToManyField(
                blank=True, to="zrodla.kategoriaukazu", verbose_name="Kategoria"
            ),
        ),
    ]
