# Generated by Django 5.2.1 on 2025-10-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0035_delete_kategoriaedyktu_alter_edykt_kategorie"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KategoriaUkazu",
            new_name="KategoriaUkazuLubEdyktu",
        ),
    ]
