# Generated by Django 5.2.1 on 2025-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zrodla", "0036_rename_kategoriaukazu_kategoriaukazulubedyktu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategoriaukazulubedyktu",
            options={
                "ordering": ["kategoria"],
                "verbose_name": "Kategoria ukazu/edyktu",
                "verbose_name_plural": "Kategorie ukazów/edyktów",
            },
        ),
        migrations.AlterField(
            model_name="kategoriaukazulubedyktu",
            name="kategoria",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Kategoria ukazu/edyktu",
            ),
        ),
    ]
