# Generated by Django 5.2.1 on 2025-07-23 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        (
            "osoby",
            "0011_alter_bean_pewnosc_stazu_alter_czlonek_imie_piwne_1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TypWydarzenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Typ wydarzenia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ wydarzenia",
                "verbose_name_plural": "Typy wydarzeń",
                "db_table": "kronika_typwydarzenia",
                "ordering": ["typ"],
            },
        ),
        migrations.CreateModel(
            name="TypWyjazdu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Typ wyjazdu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ wyjazdu",
                "verbose_name_plural": "Typy wyjazdów",
                "db_table": "kronika_typwyjazdu",
                "ordering": ["typ"],
            },
        ),
        migrations.CreateModel(
            name="Wydarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=255, verbose_name="Nazwa"),
                ),
                (
                    "czy_jednodniowe",
                    models.BooleanField(
                        default=True, verbose_name="Jednodniowe"
                    ),
                ),
                (
                    "data_rozpoczecia",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data rozpoczęcia",
                    ),
                ),
                (
                    "data_zakonczenia",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data zakończenia",
                    ),
                ),
                (
                    "czy_to_wyjazd",
                    models.BooleanField(
                        default=False, verbose_name="Czy to wyjazd?"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, verbose_name="Link do wydarzenia na FB"
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "miejsca",
                    models.ManyToManyField(
                        blank=True,
                        db_table="kronika_wydarzenie_miejsca",
                        to="miejsca.miejsce",
                        verbose_name="Miejsca",
                    ),
                ),
                (
                    "typ_wydarzenia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kalendarz.typwydarzenia",
                        verbose_name="Typ wydarzenia",
                    ),
                ),
                (
                    "typ_wyjazdu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kalendarz.typwyjazdu",
                        verbose_name="Typ wyjazdu",
                    ),
                ),
                (
                    "uczestnicy",
                    models.ManyToManyField(
                        blank=True,
                        db_table="kronika_wydarzenie_uczestnicy",
                        to="osoby.osoba",
                        verbose_name="Uczestnicy wydarzenia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydarzenie",
                "verbose_name_plural": "Wydarzenia",
                "db_table": "kronika_wydarzenie",
                "ordering": ["-data_rozpoczecia"],
            },
        ),
        migrations.CreateModel(
            name="ObrazWydarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tytul",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tytuł"
                    ),
                ),
                (
                    "obraz",
                    models.ImageField(
                        upload_to="kronika/wydarzenia/",
                        verbose_name="Dodaj obraz",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "widoczne_osoby",
                    models.ManyToManyField(
                        blank=True,
                        db_table="kronika_obrazwydarzenie_widoczne_osoby",
                        to="osoby.osoba",
                        verbose_name="Widoczne osoby",
                    ),
                ),
                (
                    "wydarzenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdjecia_z_wydarzenia",
                        to="kalendarz.wydarzenie",
                        verbose_name="Wydarzenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie z wydarzenia",
                "verbose_name_plural": "Zdjęcia z wydarzeń",
                "db_table": "kronika_obrazwydarzenie",
                "ordering": ["-wydarzenie"],
            },
        ),
        migrations.CreateModel(
            name="Zdarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=255, verbose_name="Nazwa"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "godzina",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Godzina"
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "miejsce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdarzenia_z_miejsca",
                        to="miejsca.miejsce",
                        verbose_name="Miejsce",
                    ),
                ),
                (
                    "powiazane_osoby",
                    models.ManyToManyField(
                        blank=True,
                        db_table="kronika_zdarzenie_powiazane_osoby",
                        to="osoby.osoba",
                        verbose_name="Powiązane osoby",
                    ),
                ),
                (
                    "wydarzenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdarzenia_z_wydarzenia",
                        to="kalendarz.wydarzenie",
                        verbose_name="Wydarzenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdarzenie",
                "verbose_name_plural": "Zdarzenia",
                "db_table": "kronika_zdarzenie",
                "ordering": ["-data", "nazwa"],
            },
        ),
        migrations.CreateModel(
            name="ObrazZdarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tytul",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tytuł"
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data wykonania",
                    ),
                ),
                (
                    "obraz",
                    models.ImageField(
                        upload_to="kronika/zdarzenia/",
                        verbose_name="Dodaj obraz",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "miejsce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdjecia_miejsca",
                        to="miejsca.miejsce",
                        verbose_name="Miejsce",
                    ),
                ),
                (
                    "widoczne_osoby",
                    models.ManyToManyField(
                        blank=True,
                        db_table="kronika_obrazzdarzenie_widoczne_osoby",
                        to="osoby.osoba",
                        verbose_name="Widoczne osoby",
                    ),
                ),
                (
                    "zdarzenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdjecia_ze_zdarzenia",
                        to="kalendarz.zdarzenie",
                        verbose_name="Zdarzenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie ze zdarzenia",
                "verbose_name_plural": "Zdjęcia ze zdarzeń",
                "db_table": "kronika_obrazzdarzenie",
                "ordering": ["-data"],
            },
        ),
    ]
