# Generated by Django 5.2.1 on 2025-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0001_initial"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        (
            "osoby",
            "0011_alter_bean_pewnosc_stazu_alter_czlonek_imie_piwne_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="obrazwydarzenie",
            name="widoczne_osoby",
            field=models.ManyToManyField(
                blank=True, to="osoby.osoba", verbose_name="Widoczne osoby"
            ),
        ),
        migrations.AlterField(
            model_name="obrazzdarzenie",
            name="widoczne_osoby",
            field=models.ManyToManyField(
                blank=True, to="osoby.osoba", verbose_name="Widoczne osoby"
            ),
        ),
        migrations.AlterField(
            model_name="wydarzenie",
            name="miejsca",
            field=models.ManyToManyField(
                blank=True, to="miejsca.miejsce", verbose_name="Miejsca"
            ),
        ),
        migrations.AlterField(
            model_name="wydarzenie",
            name="uczestnicy",
            field=models.ManyToManyField(
                blank=True,
                to="osoby.osoba",
                verbose_name="Uczestnicy wydarzenia",
            ),
        ),
        migrations.AlterField(
            model_name="zdarzenie",
            name="powiazane_osoby",
            field=models.ManyToManyField(
                blank=True, to="osoby.osoba", verbose_name="Powiązane osoby"
            ),
        ),
        migrations.AlterModelTable(
            name="obrazwydarzenie",
            table=None,
        ),
        migrations.AlterModelTable(
            name="obrazzdarzenie",
            table=None,
        ),
        migrations.AlterModelTable(
            name="typwydarzenia",
            table=None,
        ),
        migrations.AlterModelTable(
            name="typwyjazdu",
            table=None,
        ),
        migrations.AlterModelTable(
            name="wydarzenie",
            table=None,
        ),
        migrations.AlterModelTable(
            name="zdarzenie",
            table=None,
        ),
    ]
