# Generated by Django 5.2.1 on 2025-07-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0002_alter_obrazwydarzenie_widoczne_osoby_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="miejsce",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="widoczne_osoby",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="zdarzenie",
        ),
        migrations.DeleteModel(
            name="ObrazWydarzenie",
        ),
        migrations.DeleteModel(
            name="ObrazZdarzenie",
        ),
    ]
