# Generated by Django 5.2.1 on 2025-08-15 16:56

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("kalendarz", "0003_remove_obrazzdarzenie_miejsce_and_more"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        ("osoby", "0026_alter_komisjarewizyjna_sklad"),
    ]

    operations = [
        migrations.CreateModel(
            name="WydarzenieKalendarzowe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(max_length=255, verbose_name="Nazwa"),
                ),
                (
                    "data_rozpoczecia",
                    models.DateField(
                        default=datetime.datetime(
                            2025,
                            8,
                            15,
                            16,
                            56,
                            40,
                            826772,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Data rozpoczecia",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, verbose_name="Link do wydarzenia na FB"
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydarzenie kalendarzowe",
                "verbose_name_plural": "Wydarzenia kalendarzowe",
                "ordering": ["-data_rozpoczecia"],
            },
        ),
        migrations.CreateModel(
            name="WydarzenieDummy",
            fields=[
                (
                    "wydarzeniekalendarzowe_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kalendarz.wydarzeniekalendarzowe",
                    ),
                ),
                (
                    "czy_jednodniowe",
                    models.BooleanField(
                        default=True, verbose_name="Jednodniowe"
                    ),
                ),
                (
                    "data_zakonczenia",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data zakończenia",
                    ),
                ),
                (
                    "czy_to_wyjazd",
                    models.BooleanField(
                        default=False, verbose_name="Czy to wyjazd?"
                    ),
                ),
                (
                    "miejsca",
                    models.ManyToManyField(
                        blank=True,
                        to="miejsca.miejsce",
                        verbose_name="Miejsca",
                    ),
                ),
                (
                    "typ_wydarzenia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kalendarz.typwydarzenia",
                        verbose_name="Typ wydarzenia",
                    ),
                ),
                (
                    "typ_wyjazdu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kalendarz.typwyjazdu",
                        verbose_name="Typ wyjazdu",
                    ),
                ),
                (
                    "uczestnicy",
                    models.ManyToManyField(
                        blank=True,
                        to="osoby.osoba",
                        verbose_name="Uczestnicy wydarzenia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydarzenie",
                "verbose_name_plural": "Wydarzenia",
                "ordering": ["-data_rozpoczecia"],
            },
            bases=("kalendarz.wydarzeniekalendarzowe",),
        ),
    ]
