# Generated by Django 5.2.1 on 2025-08-22 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0004_wydarzeniekalendarzowe_wydarzeniedummy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wydarzeniekalendarzowe",
            name="data_rozpoczecia",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data rozpoczecia"
            ),
        ),
        migrations.AlterField(
            model_name="zdarzenie",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zdarzenia_z_wydarzenia",
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Wydarzenie",
            ),
        ),
    ]
