# Generated by Django 5.2.1 on 2025-08-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "kalendarz",
            "0005_alter_wydarzeniekalendarzowe_data_rozpoczecia_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wydarzeniedummy",
            options={
                "ordering": ["-data_rozpoczecia"],
                "verbose_name": "Wydarzenie dummy",
                "verbose_name_plural": "Wydarzenia dummy",
            },
        ),
        migrations.DeleteModel(
            name="Wydarzenie",
        ),
    ]
