# Generated by Django 5.2.1 on 2025-08-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0006_alter_wydarzeniedummy_options_delete_wydarzenie"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        ("osoby", "0027_alter_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WydarzenieDummy",
            new_name="Wydarzenie",
        ),
        migrations.AlterModelOptions(
            name="wydarzenie",
            options={
                "ordering": ["-data_rozpoczecia"],
                "verbose_name": "Wydarzenie",
                "verbose_name_plural": "Wydarzenia",
            },
        ),
    ]
