# Generated by Django 5.2.1 on 2025-08-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0007_rename_wydarzeniedummy_wydarzenie_and_more"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        ("osoby", "0027_alter_czlonek_depositio_beanorum"),
        ("spiewnik", "0002_piosenka_tekst_alternatywny"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositioBeanorum",
            fields=[
                (
                    "wydarzeniekalendarzowe_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kalendarz.wydarzeniekalendarzowe",
                    ),
                ),
                (
                    "chrzczeni",
                    models.ManyToManyField(
                        blank=True, to="osoby.osoba", verbose_name="Chrzczeni"
                    ),
                ),
                (
                    "hymn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spiewnik.piosenka",
                        verbose_name="Odśpiewany przez beanów hymn",
                    ),
                ),
                (
                    "miejsce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="miejsca.miejsce",
                        verbose_name="Miejsce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depositio Beanorum",
                "verbose_name_plural": "Depositio Beanorum",
                "ordering": ["-data_rozpoczecia"],
            },
            bases=("kalendarz.wydarzeniekalendarzowe",),
        ),
    ]
