# Generated by Django 5.2.1 on 2025-08-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0008_depositiobeanorum"),
        ("osoby", "0027_alter_czlonek_depositio_beanorum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositiobeanorum",
            name="chrzczeni",
            field=models.ManyToManyField(
                blank=True, to="osoby.czlonek", verbose_name="Chrzczeni"
            ),
        ),
    ]
