# Generated by Django 5.2.1 on 2025-08-24 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0009_alter_depositiobeanorum_chrzczeni"),
        ("zrodla", "0011_alter_edykt_numer_alter_ukaz_numer"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositiobeanorum",
            name="dokument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.dokument",
                verbose_name="Dokument chrzcielny",
            ),
        ),
    ]
