# Generated by Django 5.2.1 on 2025-08-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0011_chrzest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chrzest",
        ),
    ]
