# Generated by Django 5.2.1 on 2025-08-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0012_delete_chrzest"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        ("osoby", "0034_egzekutor"),
        (
            "spiewnik",
            "0003_alter_piosenka_autor_alter_piosenka_tekst_and_more",
        ),
        ("zrodla", "0015_remove_rozliczenie_transakcja"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DepositioBeanorum",
            new_name="Chrzest",
        ),
    ]
