# Generated by Django 5.2.1 on 2025-08-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0013_rename_depositiobeanorum_chrzest"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositioBeanorum",
            fields=[
                (
                    "chrzest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kalendarz.chrzest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depositio Beanorum",
                "verbose_name_plural": "Depositio Beanorum",
                "ordering": ["-data_rozpoczecia"],
            },
            bases=("kalendarz.chrzest",),
        ),
    ]
