# Generated by Django 5.2.1 on 2025-08-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0014_depositiobeanorum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chrzest",
            options={
                "ordering": ["-data_rozpoczecia"],
                "verbose_name": "Chrzest",
                "verbose_name_plural": "Chrzty",
            },
        ),
        migrations.DeleteModel(
            name="DepositioBeanorum",
        ),
    ]
