# Generated by Django 5.2.1 on 2025-08-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0016_rename_chrzest_depositiobeanorum"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        ("osoby", "0034_egzekutor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depositiobeanorum",
            options={
                "ordering": ["-data_rozpoczecia"],
                "verbose_name": "Depositio Beanorum",
                "verbose_name_plural": "Depositio Beanorum",
            },
        ),
        migrations.CreateModel(
            name="Chrzest",
            fields=[
                (
                    "wydarzeniekalendarzowe_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kalendarz.wydarzeniekalendarzowe",
                    ),
                ),
                (
                    "chrzczeni",
                    models.ManyToManyField(
                        blank=True,
                        to="osoby.czlonek",
                        verbose_name="Chrzczeni",
                    ),
                ),
                (
                    "miejsce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="miejsca.miejsce",
                        verbose_name="Miejsce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chrzest",
                "verbose_name_plural": "Chrzty",
                "ordering": ["-data_rozpoczecia"],
            },
            bases=("kalendarz.wydarzeniekalendarzowe",),
        ),
    ]
