# Generated by Django 5.2.1 on 2025-08-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0017_alter_depositiobeanorum_options_chrzest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chrzest",
        ),
    ]
