# Generated by Django 5.2.1 on 2025-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0019_rename_depositiobeanorum_chrzest_and_more"),
        ("osoby", "0041_rename_depositio_beanorum_czlonek_chrzest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chrzest",
            name="chrzczeni",
            field=models.ManyToManyField(
                blank=True,
                related_name="chrzest_osoby",
                to="osoby.czlonek",
                verbose_name="Chrzczeni",
            ),
        ),
    ]
