# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0020_alter_chrzest_chrzczeni"),
    ]

    operations = [
        migrations.AddField(
            model_name="typwydarzenia",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="typwyjazdu",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="wydarzeniekalendarzowe",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="zdarzenie",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
