# Generated by Django 5.2.1 on 2025-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0022_typwydarzenia_fields_positions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wydarzeniekalendarzowe",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do wydarzenia na FB"
            ),
        ),
        migrations.AlterField(
            model_name="wydarzeniekalendarzowe",
            name="opis",
            field=models.TextField(blank=True, null=True, verbose_name="Opis"),
        ),
    ]
