# Generated by Django 5.2.1 on 2025-09-08 13:36

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0023_alter_wydarzeniekalendarzowe_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="typwydarzenia",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="typwyjazdu",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="wydarzeniekalendarzowe",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="zdarzenie",
            name="tsv",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
