# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0025_typwydarzenia_search_dict_typwyjazdu_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typwydarzenia",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="typwydarzenia",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="typwyjazdu",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="typwyjazdu",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="wydarzeniekalendarzowe",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="wydarzeniekalendarzowe",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="zdarzenie",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="zdarzenie",
            name="search_dict",
        ),
    ]
