# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "kalendarz",
            "0027_typwydarzenia_search_dict_typwyjazdu_search_dict_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typwydarzenia",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="typwyjazdu",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="wydarzeniekalendarzowe",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="zdarzenie",
            name="search_text",
        ),
    ]
