# Generated by Django 5.2.1 on 2025-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czapki', '0002_alter_czapka_options_remove_czapka_uczelnia_and_more'),
        ('miejsca', '0004_miejsce_zamkniete_na_stale_alter_miejsce_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajCzapki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=40, verbose_name='Nazwa')),
                ('powod_koloru', models.CharField(blank=True, max_length=100, verbose_name='Od czego zależy kolor')),
                ('kraje', models.ManyToManyField(blank=True, null=True, to='miejsca.kraj', verbose_name='Kraje występowania')),
            ],
            options={
                'verbose_name': 'Rodzaj czapki studenckiej',
                'verbose_name_plural': 'Rodzaje czapek studenckich',
                'ordering': ['nazwa'],
            },
        ),
    ]
