# Generated by Django 5.2.1 on 2025-08-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0004_alter_rodzajczapki_kraje"),
        ("osoby", "0034_egzekutor"),
        ("zrodla", "0015_remove_rozliczenie_transakcja"),
    ]

    operations = [
        migrations.CreateModel(
            name="CzapkaHonorisCausa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaslugi",
                    models.TextField(blank=True, verbose_name="Zasługi"),
                ),
                (
                    "dokument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zrodla.dokument",
                        verbose_name="Dokument",
                    ),
                ),
                (
                    "wlasciciel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="osoby.osoba",
                        verbose_name="Właściciel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posiadacz czapki Honoris Causa",
                "verbose_name_plural": "Posiadacze czapek Honoris Causa",
                "ordering": ["wlasciciel"],
            },
        ),
    ]
