# Generated by Django 5.2.1 on 2025-08-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0005_czapkahonoriscausa"),
        ("zrodla", "0015_remove_rozliczenie_transakcja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czapkahonoriscausa",
            name="dokument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zrodla.dokument",
                verbose_name="Dokument nadający",
            ),
        ),
    ]
