# Generated by Django 5.2.1 on 2025-08-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0006_alter_czapkahonoriscausa_dokument"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CzapkaHonorisCausa",
        ),
    ]
