# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0007_delete_czapkahonoriscausa"),
    ]

    operations = [
        migrations.AddField(
            model_name="czapka",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="rodzajczapki",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
