# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0008_czapka_search_text_rodzajczapki_search_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="czapka",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="rodzajczapki",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
