# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0011_czapka_search_dict_rodzajczapki_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="czapka",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="czapka",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="rodzajczapki",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="rodzajczapki",
            name="search_dict",
        ),
    ]
