# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("czapki", "0013_czapka_search_dict_rodzajczapki_search_dict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="czapka",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="rodzajczapki",
            name="search_text",
        ),
    ]
