# Generated by Django 5.2.1 on 2025-07-29 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kalendarz", "0003_remove_obrazzdarzenie_miejsce_and_more"),
        ("miejsca", "0004_miejsce_zamkniete_na_stale_alter_miejsce_adres"),
        ("osoby", "0024_set_polymorphic_ctype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObrazWydarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tytul",
                    models.CharField(max_length=100, verbose_name="Tytuł"),
                ),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data wykonania",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "obraz",
                    models.ImageField(
                        upload_to="images/kalendarz/wydarzenie/",
                        verbose_name="Dodaj obraz",
                    ),
                ),
                (
                    "widoczne_osoby",
                    models.ManyToManyField(
                        blank=True,
                        to="osoby.osoba",
                        verbose_name="Widoczne osoby",
                    ),
                ),
                (
                    "wydarzenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdjecia_z_wydarzenia",
                        to="kalendarz.wydarzenie",
                        verbose_name="Wydarzenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie z wydarzenia",
                "verbose_name_plural": "Zdjęcia z wydarzeń",
                "ordering": ["-wydarzenie"],
            },
        ),
        migrations.CreateModel(
            name="ObrazZdarzenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tytul",
                    models.CharField(max_length=100, verbose_name="Tytuł"),
                ),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data wykonania",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "obraz",
                    models.ImageField(
                        upload_to="images/kalendarz/zdarzenie/",
                        verbose_name="Dodaj obraz",
                    ),
                ),
                (
                    "miejsce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdjecia_miejsca",
                        to="miejsca.miejsce",
                        verbose_name="Miejsce",
                    ),
                ),
                (
                    "widoczne_osoby",
                    models.ManyToManyField(
                        blank=True,
                        to="osoby.osoba",
                        verbose_name="Widoczne osoby",
                    ),
                ),
                (
                    "zdarzenie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zdjecia_ze_zdarzenia",
                        to="kalendarz.zdarzenie",
                        verbose_name="Zdarzenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie ze zdarzenia",
                "verbose_name_plural": "Zdjęcia ze zdarzeń",
                "ordering": ["-data"],
            },
        ),
    ]
