# Generated by Django 5.2.1 on 2025-07-29 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="data",
        ),
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="id",
        ),
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="opis",
        ),
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="tytul",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="data",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="id",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="opis",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="tytul",
        ),
        migrations.CreateModel(
            name="Obraz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tytul", models.CharField(max_length=100, verbose_name="Tytuł")),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data wykonania",
                    ),
                ),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="obrazwydarzenie",
            name="obraz_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="multimedia.obraz",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="obrazzdarzenie",
            name="obraz_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="multimedia.obraz",
            ),
            preserve_default=False,
        ),
    ]
