# Generated by Django 5.2.1 on 2025-08-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendarz", "0005_alter_wydarzeniekalendarzowe_data_rozpoczecia_and_more"),
        ("multimedia", "0002_remove_obrazwydarzenie_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obrazwydarzenie",
            name="wydarzenie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zdjecia_z_wydarzenia",
                to="kalendarz.wydarzeniekalendarzowe",
                verbose_name="Wydarzenie",
            ),
        ),
    ]
