# Generated by Django 5.2.1 on 2025-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0003_alter_obrazwydarzenie_wydarzenie"),
    ]

    operations = [
        migrations.AddField(
            model_name="obrazwydarzenie",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="obrazzdarzenie",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
