# Generated by Django 5.2.1 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0004_obrazwydarzenie_search_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obrazwydarzenie",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="obrazzdarzenie",
            name="fields_positions",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
