# Generated by Django 5.2.1 on 2025-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0006_obrazwydarzenie_tsv_obrazzdarzenie_tsv"),
    ]

    operations = [
        migrations.AddField(
            model_name="obrazwydarzenie",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="obrazzdarzenie",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
