# Generated by Django 5.2.1 on 2025-09-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0007_obrazwydarzenie_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="fields_positions",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="search_dict",
        ),
    ]
