# Generated by Django 5.2.1 on 2025-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "multimedia",
            "0008_remove_obrazwydarzenie_fields_positions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="obrazwydarzenie",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="obrazzdarzenie",
            name="search_dict",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
