# Generated by Django 5.2.1 on 2025-09-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0009_obrazwydarzenie_search_dict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="search_text",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="search_text",
        ),
    ]
