# Generated by Django 5.2.1 on 2025-09-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0010_remove_obrazwydarzenie_search_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="obrazwydarzenie",
            name="tsv",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="search_dict",
        ),
        migrations.RemoveField(
            model_name="obrazzdarzenie",
            name="tsv",
        ),
    ]
